In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("./star_original.csv")
df

C:\Users\10728\AppData\Local\Temp\ipykernel_26364\2623927726.py:1: DtypeWarning: Columns (21,22,23,24,25,26,73,74,75,143,144,145,146,147,148,149,150,151,152,153,154,155,218,230,231,283,284,285,286,349,350,375,376,594,595,596,597,598,599,600,601,602,603,604,605,606,662,665,671) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("./star_original.csv")

,uid,star_level,COUNT(dm_v_as_djk_info),MAX(dm_v_as_djk_info.bal),MAX(dm_v_as_djk_info.cred_limit),MAX(dm_v_as_djk_info.deposit),MAX(dm_v_as_djk_info.dlay_amt),MAX(dm_v_as_djk_info.five_class),MAX(dm_v_as_djk_info.over_draft),MEAN(dm_v_as_djk_info.bal),...,STD(v_tr_shop_mx. tran_sts),SUM(v_tr_shop_mx. current_status),SUM(v_tr_shop_mx. tran_sts),COUNT(pri_credit_info),MAX(pri_credit_info.credit_level),MEAN(pri_credit_info.credit_level),MIN(pri_credit_info.credit_level),SKEW(pri_credit_info.credit_level),STD(pri_credit_info.credit_level),SUM(pri_credit_info.credit_level)
0,130581199112042682,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0
1,130635198511165690,3,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0
2,130684198606215045,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,1.0,60.0,60.0,60.0,NaN,NaN,60.0
3,130802201408149594,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0
4,140902198607183528,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290653,654324198006010321,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0
290654,654326198608203393,2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,1.0,60.0,60.0,60.0,NaN,NaN,60.0
290655,810000200811269255,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0
290656,830000197007029225,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0
290657,830000200706189396,-1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0

In [5]:
for column in df.columns.to_list():
    print(column,":")
    missing_count = df[column].isnull().sum()
    # print(missing_count)
    total_count = 290658
    # print(total_count)
    missing_percent = missing_count / total_count
    print(missing_percent)
    if(missing_percent>0.7):
        df = df.drop(column,axis=1)
        print("deleted\n")

uid :
0.0
 star_level :
0.0
COUNT(dm_v_as_djk_info) :
0.0
MAX(dm_v_as_djk_info.bal) :
0.9481555642714118
deleted

MAX(dm_v_as_djk_info.cred_limit) :
0.9481555642714118
deleted

MAX(dm_v_as_djk_info.deposit) :
0.9481555642714118
deleted

MAX(dm_v_as_djk_info.dlay_amt) :
0.9481555642714118
deleted

MAX(dm_v_as_djk_info.five_class) :
0.9481555642714118
deleted

MAX(dm_v_as_djk_info.over_draft) :
0.9481555642714118
deleted

MEAN(dm_v_as_djk_info.bal) :
0.9481555642714118
deleted

MEAN(dm_v_as_djk_info.cred_limit) :
0.9481555642714118
deleted

MEAN(dm_v_as_djk_info.deposit) :
0.9481555642714118
deleted

MEAN(dm_v_as_djk_info.dlay_amt) :
0.9481555642714118
deleted

MEAN(dm_v_as_djk_info.five_class) :
0.9481555642714118
deleted

MEAN(dm_v_as_djk_info.over_draft) :
0.9481555642714118
deleted

MIN(dm_v_as_djk_info.bal) :
0.9481555642714118
deleted

MIN(dm_v_as_djk_info.cred_limit) :
0.9481555642714118
deleted

MIN(dm_v_as_djk_info.deposit) :
0.9481555642714118
deleted

MIN(dm_v_as_djk_info.dlay_amt) :
0.9481555642714118
deleted

MIN(dm_v_as_djk_info.five_class) :
0.9481555642714118
deleted

MIN(dm_v_as_djk_info.over_draft) :
0.9481555642714118
deleted

MODE(dm_v_as_djk_info.card_sts) :
0.9770142229011416
deleted

MODE(dm_v_as_djk_info.is_deposit) :
0.9481555642714118
deleted

MODE(dm_v_as_djk_info.is_etc) :
0.9481555642714118
deleted

MODE(dm_v_as_djk_info.is_purchse) :
0.9481555642714118
deleted

MODE(dm_v_as_djk_info.is_transfer) :
0.9481555642714118
deleted

MODE(dm_v_as_djk_info.is_withdrw) :
0.9481555642714118
deleted

NUM_UNIQUE(dm_v_as_djk_info.card_sts) :
0.9481555642714118
deleted

NUM_UNIQUE(dm_v_as_djk_info.is_deposit) :
0.9481555642714118
deleted

NUM_UNIQUE(dm_v_as_djk_info.is_etc) :
0.9481555642714118
deleted

NUM_UNIQUE(dm_v_as_djk_info.is_purchse) :
0.9481555642714118
deleted

NUM_UNIQUE(dm_v_as_djk_info.is_transfer) :
0.9481555642714118
deleted

NUM_UNIQUE(dm_v_as_djk_info.is_withdrw) :
0.9481555642714118
deleted

SKEW(dm_v_as_djk_info.bal) :
0.9997694885397959
deleted

SKEW(dm_v_as_djk_info.cred_limit) :
0.9997694885397959
deleted

SKEW(dm_v_as_djk_info.deposit) :
0.9997694885397959
deleted

SKEW(dm_v_as_djk_info.dlay_amt) :
0.9997694885397959
deleted

SKEW(dm_v_as_djk_info.five_class) :
0.9997694885397959
deleted

SKEW(dm_v_as_djk_info.over_draft) :
0.9997694885397959
deleted

STD(dm_v_as_djk_info.bal) :
0.9970033510173468
deleted

STD(dm_v_as_djk_info.cred_limit) :
0.9970033510173468
deleted

STD(dm_v_as_djk_info.deposit) :
0.9970033510173468
deleted

STD(dm_v_as_djk_info.dlay_amt) :
0.9970033510173468
deleted

STD(dm_v_as_djk_info.five_class) :
0.9970033510173468
deleted

STD(dm_v_as_djk_info.over_draft) :
0.9970033510173468
deleted

SUM(dm_v_as_djk_info.bal) :
0.0
SUM(dm_v_as_djk_info.cred_limit) :
0.0
SUM(dm_v_as_djk_info.deposit) :
0.0
SUM(dm_v_as_djk_info.dlay_amt) :
0.0
SUM(dm_v_as_djk_info.five_class) :
0.0
SUM(dm_v_as_djk_info.over_draft) :
0.0
COUNT(dm_v_as_djkfq_info) :
0.0
MAX(dm_v_as_djkfq_info.instl_cnt) :
0.9988061570643162
deleted

MAX(dm_v_as_djkfq_info.mp_number) :
0.9988061570643162
deleted

MAX(dm_v_as_djkfq_info.mp_number.1) :
0.9988061570643162
deleted

MAX(dm_v_as_djkfq_info.rec_fee) :
0.9988061570643162
deleted

MAX(dm_v_as_djkfq_info.rem_fee) :
0.9988061570643162
deleted

MAX(dm_v_as_djkfq_info.total_amt) :
0.9988061570643162
deleted

MAX(dm_v_as_djkfq_info.total_mths) :
0.9988061570643162
deleted

MEAN(dm_v_as_djkfq_info.instl_cnt) :
0.9988061570643162
deleted

MEAN(dm_v_as_djkfq_info.mp_number) :
0.9988061570643162
deleted

MEAN(dm_v_as_djkfq_info.mp_number.1) :
0.9988061570643162
deleted

MEAN(dm_v_as_djkfq_info.rec_fee) :
0.9988061570643162
deleted

MEAN(dm_v_as_djkfq_info.rem_fee) :
0.9988061570643162
deleted

MEAN(dm_v_as_djkfq_info.total_amt) :
0.9988061570643162
deleted

MEAN(dm_v_as_djkfq_info.total_mths) :
0.9988061570643162
deleted

MIN(dm_v_as_djkfq_info.instl_cnt) :
0.9988061570643162
deleted

MIN(dm_v_as_djkfq_info.mp_number) :
0.9988061570643162
deleted

MIN(dm_v_as_djkfq_info.mp_number.1) :
0.9988061570643162
deleted

MIN(dm_v_as_djkfq_info.rec_fee) :
0.9988061570643162
deleted

MIN(dm_v_as_djkfq_info.rem_fee) :
0.9988061570643162
deleted

MIN(dm_v_as_djkfq_info.total_amt) :
0.9988061570643162
deleted

MIN(dm_v_as_djkfq_info.total_mths) :
0.9988061570643162
deleted

MODE(dm_v_as_djkfq_info.mp_status) :
0.9988061570643162
deleted

MODE(dm_v_as_djkfq_info.mp_type) :
0.9988061570643162
deleted

MODE(dm_v_as_djkfq_info.recom_no) :
0.9988061570643162
deleted

NUM_UNIQUE(dm_v_as_djkfq_info.mp_status) :
0.9988061570643162
deleted

NUM_UNIQUE(dm_v_as_djkfq_info.mp_type) :
0.9988061570643162
deleted

NUM_UNIQUE(dm_v_as_djkfq_info.recom_no) :
0.9988061570643162
deleted

SKEW(dm_v_as_djkfq_info.instl_cnt) :
0.9999690357740024
deleted

SKEW(dm_v_as_djkfq_info.mp_number) :
0.9999690357740024
deleted

SKEW(dm_v_as_djkfq_info.mp_number.1) :
0.9999690357740024
deleted

SKEW(dm_v_as_djkfq_info.rec_fee) :
0.9999690357740024
deleted

SKEW(dm_v_as_djkfq_info.rem_fee) :
0.9999690357740024
deleted

SKEW(dm_v_as_djkfq_info.total_amt) :
0.9999690357740024
deleted

SKEW(dm_v_as_djkfq_info.total_mths) :
0.9999690357740024
deleted

STD(dm_v_as_djkfq_info.instl_cnt) :
0.999879583565565
deleted

STD(dm_v_as_djkfq_info.mp_number) :
0.999879583565565
deleted

STD(dm_v_as_djkfq_info.mp_number.1) :
0.999879583565565
deleted

STD(dm_v_as_djkfq_info.rec_fee) :
0.999879583565565
deleted

STD(dm_v_as_djkfq_info.rem_fee) :
0.999879583565565
deleted

STD(dm_v_as_djkfq_info.total_amt) :
0.999879583565565
deleted

STD(dm_v_as_djkfq_info.total_mths) :
0.999879583565565
deleted

SUM(dm_v_as_djkfq_info.instl_cnt) :
0.0
SUM(dm_v_as_djkfq_info.mp_number) :
0.0
SUM(dm_v_as_djkfq_info.mp_number.1) :
0.0
SUM(dm_v_as_djkfq_info.rec_fee) :
0.0
SUM(dm_v_as_djkfq_info.rem_fee) :
0.0
SUM(dm_v_as_djkfq_info.total_amt) :
0.0
SUM(dm_v_as_djkfq_info.total_mths) :
0.0
COUNT(dm_v_tr_contract_mx) :
0.0
MAX(dm_v_tr_contract_mx.buss_amt) :
0.861297469878689
deleted

MAX(dm_v_tr_contract_mx.dlay_days) :
0.861297469878689
deleted

MAX(dm_v_tr_contract_mx.due_intr_days) :
0.861297469878689
deleted

MAX(dm_v_tr_contract_mx.fine_intr_int) :
0.861297469878689
deleted

MAX(dm_v_tr_contract_mx.fine_pr_int) :
0.861297469878689
deleted

MAX(dm_v_tr_contract_mx.frz_amt) :
0.861297469878689
deleted

MAX(dm_v_tr_contract_mx.is_bad) :
1.0
deleted

MAX(dm_v_tr_contract_mx.loan_pert) :
0.861297469878689
deleted

MAX(dm_v_tr_contract_mx.owed_int_in) :
0.861297469878689
deleted

MAX(dm_v_tr_contract_mx.owed_int_out) :
0.861297469878689
deleted

MAX(dm_v_tr_contract_mx.pay_times) :
0.861297469878689
deleted

MAX(dm_v_tr_contract_mx.term_day) :
0.861297469878689
deleted

MAX(dm_v_tr_contract_mx.term_mth) :
0.861297469878689
deleted

MAX(dm_v_tr_contract_mx.term_year) :
0.861297469878689
deleted

MEAN(dm_v_tr_contract_mx.buss_amt) :
0.861297469878689
deleted

MEAN(dm_v_tr_contract_mx.dlay_days) :
0.861297469878689
deleted

MEAN(dm_v_tr_contract_mx.due_intr_days) :
0.861297469878689
deleted

MEAN(dm_v_tr_contract_mx.fine_intr_int) :
0.861297469878689
deleted

MEAN(dm_v_tr_contract_mx.fine_pr_int) :
0.861297469878689
deleted

MEAN(dm_v_tr_contract_mx.frz_amt) :
0.861297469878689
deleted

MEAN(dm_v_tr_contract_mx.is_bad) :
1.0
deleted

MEAN(dm_v_tr_contract_mx.loan_pert) :
0.861297469878689
deleted

MEAN(dm_v_tr_contract_mx.owed_int_in) :
0.861297469878689
deleted

MEAN(dm_v_tr_contract_mx.owed_int_out) :
0.861297469878689
deleted

MEAN(dm_v_tr_contract_mx.pay_times) :
0.861297469878689
deleted

MEAN(dm_v_tr_contract_mx.term_day) :
0.861297469878689
deleted

MEAN(dm_v_tr_contract_mx.term_mth) :
0.861297469878689
deleted

MEAN(dm_v_tr_contract_mx.term_year) :
0.861297469878689
deleted

MIN(dm_v_tr_contract_mx.buss_amt) :
0.861297469878689
deleted

MIN(dm_v_tr_contract_mx.dlay_days) :
0.861297469878689
deleted

MIN(dm_v_tr_contract_mx.due_intr_days) :
0.861297469878689
deleted

MIN(dm_v_tr_contract_mx.fine_intr_int) :
0.861297469878689
deleted

MIN(dm_v_tr_contract_mx.fine_pr_int) :
0.861297469878689
deleted

MIN(dm_v_tr_contract_mx.frz_amt) :
0.861297469878689
deleted

MIN(dm_v_tr_contract_mx.is_bad) :
1.0
deleted

MIN(dm_v_tr_contract_mx.loan_pert) :
0.861297469878689
deleted

MIN(dm_v_tr_contract_mx.owed_int_in) :
0.861297469878689

deleted

MIN(dm_v_tr_contract_mx.owed_int_out) :
0.861297469878689
deleted

MIN(dm_v_tr_contract_mx.pay_times) :
0.861297469878689
deleted

MIN(dm_v_tr_contract_mx.term_day) :
0.861297469878689
deleted

MIN(dm_v_tr_contract_mx.term_mth) :
0.861297469878689
deleted

MIN(dm_v_tr_contract_mx.term_year) :
0.861297469878689
deleted

MODE(dm_v_tr_contract_mx.apply_type) :
0.8651817600066057
deleted

MODE(dm_v_tr_contract_mx.curr_type) :
0.861297469878689
deleted

MODE(dm_v_tr_contract_mx.direction) :
0.861297469878689
deleted

MODE(dm_v_tr_contract_mx.finsh_type) :
0.861297469878689
deleted

MODE(dm_v_tr_contract_mx.five_class) :
0.861297469878689
deleted

MODE(dm_v_tr_contract_mx.is_credit_cyc) :
0.861297469878689
deleted

MODE(dm_v_tr_contract_mx.is_vc_vouch) :
0.861297469878689
deleted

MODE(dm_v_tr_contract_mx.loan_use) :
0.8805778612665056
deleted

MODE(dm_v_tr_contract_mx.loan_use_add) :
0.9420487308107811
deleted

MODE(dm_v_tr_contract_mx.occur_type) :
0.861297469878689
deleted

MODE(dm_v_tr_contract_mx.pay_source) :
0.9946466293719767
deleted

MODE(dm_v_tr_contract_mx.pay_type) :
0.861297469878689
deleted

MODE(dm_v_tr_contract_mx.vouch_type) :
0.861297469878689
deleted

NUM_UNIQUE(dm_v_tr_contract_mx.apply_type) :
0.861297469878689
deleted

NUM_UNIQUE(dm_v_tr_contract_mx.curr_type) :
0.861297469878689
deleted

NUM_UNIQUE(dm_v_tr_contract_mx.direction) :
0.861297469878689
deleted

NUM_UNIQUE(dm_v_tr_contract_mx.finsh_type) :
0.861297469878689
deleted

NUM_UNIQUE(dm_v_tr_contract_mx.five_class) :
0.861297469878689
deleted

NUM_UNIQUE(dm_v_tr_contract_mx.is_credit_cyc) :
0.861297469878689
deleted

NUM_UNIQUE(dm_v_tr_contract_mx.is_vc_vouch) :
0.861297469878689
deleted

NUM_UNIQUE(dm_v_tr_contract_mx.loan_use) :
0.861297469878689
deleted

NUM_UNIQUE(dm_v_tr_contract_mx.loan_use_add) :
0.861297469878689
deleted

NUM_UNIQUE(dm_v_tr_contract_mx.occur_type) :
0.861297469878689
deleted

NUM_UNIQUE(dm_v_tr_contract_mx.pay_source) :
0.861297469878689
deleted

NUM_UNIQUE(dm_v_tr_contract_mx.pay_type) :
0.861297469878689
deleted

NUM_UNIQUE(dm_v_tr_contract_mx.vouch_type) :
0.861297469878689
deleted

SKEW(dm_v_tr_contract_mx.buss_amt) :
0.936626550791652
deleted

SKEW(dm_v_tr_contract_mx.dlay_days) :
0.936626550791652
deleted

SKEW(dm_v_tr_contract_mx.due_intr_days) :
0.936626550791652
deleted

SKEW(dm_v_tr_contract_mx.fine_intr_int) :
0.936626550791652
deleted

SKEW(dm_v_tr_contract_mx.fine_pr_int) :
0.936626550791652
deleted

SKEW(dm_v_tr_contract_mx.frz_amt) :
0.936626550791652
deleted

SKEW(dm_v_tr_contract_mx.is_bad) :
1.0
deleted

SKEW(dm_v_tr_contract_mx.loan_pert) :
0.936626550791652
deleted

SKEW(dm_v_tr_contract_mx.owed_int_in) :
0.936626550791652
deleted

SKEW(dm_v_tr_contract_mx.owed_int_out) :
0.936626550791652
deleted

SKEW(dm_v_tr_contract_mx.pay_times) :
0.936626550791652
deleted

SKEW(dm_v_tr_contract_mx.term_day) :
0.936626550791652
deleted

SKEW(dm_v_tr_contract_mx.term_mth) :
0.936626550791652
deleted

SKEW(dm_v_tr_contract_mx.term_year) :
0.936626550791652
deleted

STD(dm_v_tr_contract_mx.buss_amt) :
0.8808496583613732
deleted

STD(dm_v_tr_contract_mx.dlay_days) :
0.8808496583613732
deleted

STD(dm_v_tr_contract_mx.due_intr_days) :
0.8808496583613732
deleted

STD(dm_v_tr_contract_mx.fine_intr_int) :
0.8808496583613732
deleted

STD(dm_v_tr_contract_mx.fine_pr_int) :
0.8808496583613732
deleted

STD(dm_v_tr_contract_mx.frz_amt) :
0.8808496583613732
deleted

STD(dm_v_tr_contract_mx.is_bad) :
1.0
deleted

STD(dm_v_tr_contract_mx.loan_pert) :
0.8808496583613732
deleted

STD(dm_v_tr_contract_mx.owed_int_in) :
0.8808496583613732
deleted

STD(dm_v_tr_contract_mx.owed_int_out) :
0.8808496583613732
deleted

STD(dm_v_tr_contract_mx.pay_times) :
0.8808496583613732
deleted

STD(dm_v_tr_contract_mx.term_day) :
0.8808496583613732
deleted

STD(dm_v_tr_contract_mx.term_mth) :
0.8808496583613732
deleted

STD(dm_v_tr_contract_mx.term_year) :
0.8808496583613732
deleted

SUM(dm_v_tr_contract_mx.buss_amt) :
0.0
SUM(dm_v_tr_contract_mx.dlay_days) :
0.0
SUM(dm_v_tr_contract_mx.due_intr_days) :
0.0
SUM(dm_v_tr_contract_mx.fine_intr_int) :
0.0
SUM(dm_v_tr_contract_mx.fine_pr_int) :
0.0
SUM(dm_v_tr_contract_mx.frz_amt) :
0.0
SUM(dm_v_tr_contract_mx.is_bad) :
0.0
SUM(dm_v_tr_contract_mx.loan_pert) :
0.0
SUM(dm_v_tr_contract_mx.owed_int_in) :
0.0
SUM(dm_v_tr_contract_mx.owed_int_out) :
0.0
SUM(dm_v_tr_contract_mx.pay_times) :
0.0
SUM(dm_v_tr_contract_mx.term_day) :
0.0
SUM(dm_v_tr_contract_mx.term_mth) :
0.0
SUM(dm_v_tr_contract_mx.term_year) :
0.0
COUNT(dm_v_tr_djk_mx) :
0.0
MAX(dm_v_tr_djk_mx.tran_amt) :
0.9691011429239863
deleted

MAX(dm_v_tr_djk_mx.tran_type) :
0.9691011429239863
deleted

MEAN(dm_v_tr_djk_mx.tran_amt) :
0.9691011429239863
deleted

MEAN(dm_v_tr_djk_mx.tran_type) :
0.9691011429239863
deleted

MIN(dm_v_tr_djk_mx.tran_amt) :
0.9691011429239863
deleted

MIN(dm_v_tr_djk_mx.tran_type) :
0.9691011429239863
deleted

MODE(dm_v_tr_djk_mx.tran_amt_sign) :
0.9691011429239863
deleted

NUM_UNIQUE(dm_v_tr_djk_mx.tran_amt_sign) :
0.9691011429239863
deleted

SKEW(dm_v_tr_djk_mx.tran_amt) :
0.9717090188468922
deleted

SKEW(dm_v_tr_djk_mx.tran_type) :
0.9717090188468922
deleted

STD(dm_v_tr_djk_mx.tran_amt) :
0.9701745694252352
deleted

STD(dm_v_tr_djk_mx.tran_type) :
0.9701745694252352
deleted

SUM(dm_v_tr_djk_mx.tran_amt) :
0.0
SUM(dm_v_tr_djk_mx.tran_type) :
0.0
COUNT(dm_v_tr_dsf_mx) :
0.0
MAX(dm_v_tr_dsf_mx.tran_amt) :
0.9946053437373132
deleted

MEAN(dm_v_tr_dsf_mx.tran_amt) :
0.9946053437373132
deleted

MIN(dm_v_tr_dsf_mx.tran_amt) :
0.9946053437373132
deleted

MODE(dm_v_tr_dsf_mx.busi_type) :
0.9946053437373132
deleted

MODE(dm_v_tr_dsf_mx.tran_sts) :
0.9946053437373132
deleted

NUM_UNIQUE(dm_v_tr_dsf_mx.busi_type) :
0.9946053437373132
deleted

NUM_UNIQUE(dm_v_tr_dsf_mx.tran_sts) :
0.9946053437373132
deleted

SKEW(dm_v_tr_dsf_mx.tran_amt) :
0.9975056595724184
deleted

STD(dm_v_tr_dsf_mx.tran_amt) :
0.9966352207749314
deleted

SUM(dm_v_tr_dsf_mx.tran_amt) :
0.0
COUNT(dm_v_tr_duebill_mx) :
0.0
MAX(dm_v_tr_duebill_mx.bad_debt_amt) :
0.9156706507304117
deleted

MAX(dm_v_tr_duebill_mx.bal) :
0.9156706507304117
deleted

MAX(dm_v_tr_duebill_mx.buss_amt) :
0.9156706507304117
deleted

MAX(dm_v_tr_duebill_mx.buss_type) :
0.9156706507304117
deleted

MAX(dm_v_tr_duebill_mx.dlay_amt) :
0.9156706507304117
deleted

MAX(dm_v_tr_duebill_mx.dlay_days) :
0.9156706507304117
deleted

MAX(dm_v_tr_duebill_mx.due_intr_days) :
0.9156706507304117
deleted

MAX(dm_v_tr_duebill_mx.dull_amt) :
0.9156706507304117
deleted

MAX(dm_v_tr_duebill_mx.fine_intr_int) :
0.9156706507304117
deleted

MAX(dm_v_tr_duebill_mx.fine_pr_int) :
0.9156706507304117
deleted

MAX(dm_v_tr_duebill_mx.loan_use) :
1.0
deleted

MAX(dm_v_tr_duebill_mx.norm_bal) :
0.9156706507304117
deleted

MAX(dm_v_tr_duebill_mx.owed_int_in) :
0.9156706507304117
deleted

MAX(dm_v_tr_duebill_mx.owed_int_out) :
0.9156706507304117
deleted

MAX(dm_v_tr_duebill_mx.pay_freq) :
0.9156706507304117
deleted

MEAN(dm_v_tr_duebill_mx.bad_debt_amt) :
0.9156706507304117
deleted

MEAN(dm_v_tr_duebill_mx.bal) :
0.9156706507304117
deleted

MEAN(dm_v_tr_duebill_mx.buss_amt) :
0.9156706507304117
deleted

MEAN(dm_v_tr_duebill_mx.buss_type) :
0.9156706507304117
deleted

MEAN(dm_v_tr_duebill_mx.dlay_amt) :
0.9156706507304117
deleted

MEAN(dm_v_tr_duebill_mx.dlay_days) :
0.9156706507304117
deleted

MEAN(dm_v_tr_duebill_mx.due_intr_days) :
0.9156706507304117
deleted

MEAN(dm_v_tr_duebill_mx.dull_amt) :
0.9156706507304117
deleted

MEAN(dm_v_tr_duebill_mx.fine_intr_int) :
0.9156706507304117
deleted

MEAN(dm_v_tr_duebill_mx.fine_pr_int) :
0.9156706507304117
deleted

MEAN(dm_v_tr_duebill_mx.loan_use) :
1.0
deleted

MEAN(dm_v_tr_duebill_mx.norm_bal) :
0.9156706507304117
deleted

MEAN(dm_v_tr_duebill_mx.owed_int_in) :
0.9156706507304117
deleted

MEAN(dm_v_tr_duebill_mx.owed_int_out) :
0.9156706507304117
deleted

MEAN(dm_v_tr_duebill_mx.pay_freq) :
0.9156706507304117
deleted

MIN(dm_v_tr_duebill_mx.bad_debt_amt) :
0.9156706507304117
deleted

MIN(dm_v_tr_duebill_mx.bal) :
0.9156706507304117
deleted

MIN(dm_v_tr_duebill_mx.buss_amt) :
0.9156706507304117
deleted

MIN(dm_v_tr_duebill_mx.buss_type) :
0.9156706507304117
deleted

MIN(dm_v_tr_duebill_mx.dlay_amt) :
0.9156706507304117

deleted

MIN(dm_v_tr_duebill_mx.dlay_days) :
0.9156706507304117
deleted

MIN(dm_v_tr_duebill_mx.due_intr_days) :
0.9156706507304117
deleted

MIN(dm_v_tr_duebill_mx.dull_amt) :
0.9156706507304117
deleted

MIN(dm_v_tr_duebill_mx.fine_intr_int) :
0.9156706507304117
deleted

MIN(dm_v_tr_duebill_mx.fine_pr_int) :
0.9156706507304117
deleted

MIN(dm_v_tr_duebill_mx.loan_use) :
1.0
deleted

MIN(dm_v_tr_duebill_mx.norm_bal) :
0.9156706507304117
deleted

MIN(dm_v_tr_duebill_mx.owed_int_in) :
0.9156706507304117
deleted

MIN(dm_v_tr_duebill_mx.owed_int_out) :
0.9156706507304117
deleted

MIN(dm_v_tr_duebill_mx.pay_freq) :
0.9156706507304117
deleted

MODE(dm_v_tr_duebill_mx.curr_type) :
0.9156706507304117
deleted

MODE(dm_v_tr_duebill_mx.pay_type) :
0.9156706507304117
deleted

MODE(dm_v_tr_duebill_mx.ten_class) :
0.9156706507304117
deleted

MODE(dm_v_tr_duebill_mx.vouch_type) :
0.9156706507304117
deleted

NUM_UNIQUE(dm_v_tr_duebill_mx.curr_type) :
0.9156706507304117
deleted

NUM_UNIQUE(dm_v_tr_duebill_mx.pay_type) :
0.9156706507304117
deleted

NUM_UNIQUE(dm_v_tr_duebill_mx.ten_class) :
0.9156706507304117
deleted

NUM_UNIQUE(dm_v_tr_duebill_mx.vouch_type) :
0.9156706507304117
deleted

SKEW(dm_v_tr_duebill_mx.bad_debt_amt) :
0.9627741194118173
deleted

SKEW(dm_v_tr_duebill_mx.bal) :
0.9627741194118173
deleted

SKEW(dm_v_tr_duebill_mx.buss_amt) :
0.9627741194118173
deleted

SKEW(dm_v_tr_duebill_mx.buss_type) :
0.9627741194118173
deleted

SKEW(dm_v_tr_duebill_mx.dlay_amt) :
0.9627741194118173
deleted

SKEW(dm_v_tr_duebill_mx.dlay_days) :
0.9627741194118173
deleted

SKEW(dm_v_tr_duebill_mx.due_intr_days) :
0.9627741194118173
deleted

SKEW(dm_v_tr_duebill_mx.dull_amt) :
0.9627741194118173
deleted

SKEW(dm_v_tr_duebill_mx.fine_intr_int) :
0.9627741194118173
deleted

SKEW(dm_v_tr_duebill_mx.fine_pr_int) :
0.9627741194118173
deleted

SKEW(dm_v_tr_duebill_mx.loan_use) :
1.0
deleted

SKEW(dm_v_tr_duebill_mx.norm_bal) :
0.9627741194118173
deleted

SKEW(dm_v_tr_duebill_mx.owed_int_in) :
0.9627741194118173
deleted

SKEW(dm_v_tr_duebill_mx.owed_int_out) :
0.9627741194118173
deleted

SKEW(dm_v_tr_duebill_mx.pay_freq) :
0.9627741194118173
deleted

STD(dm_v_tr_duebill_mx.bad_debt_amt) :
0.9496108828932973
deleted

STD(dm_v_tr_duebill_mx.bal) :
0.9496108828932973
deleted

STD(dm_v_tr_duebill_mx.buss_amt) :
0.9496108828932973
deleted

STD(dm_v_tr_duebill_mx.buss_type) :
0.9496108828932973
deleted

STD(dm_v_tr_duebill_mx.dlay_amt) :
0.9496108828932973
deleted

STD(dm_v_tr_duebill_mx.dlay_days) :
0.9496108828932973
deleted

STD(dm_v_tr_duebill_mx.due_intr_days) :
0.9496108828932973
deleted

STD(dm_v_tr_duebill_mx.dull_amt) :
0.9496108828932973
deleted

STD(dm_v_tr_duebill_mx.fine_intr_int) :
0.9496108828932973
deleted

STD(dm_v_tr_duebill_mx.fine_pr_int) :
0.9496108828932973
deleted

STD(dm_v_tr_duebill_mx.loan_use) :
1.0
deleted

STD(dm_v_tr_duebill_mx.norm_bal) :
0.9496108828932973
deleted

STD(dm_v_tr_duebill_mx.owed_int_in) :
0.9496108828932973
deleted

STD(dm_v_tr_duebill_mx.owed_int_out) :
0.9496108828932973
deleted

STD(dm_v_tr_duebill_mx.pay_freq) :
0.9496108828932973
deleted

SUM(dm_v_tr_duebill_mx.bad_debt_amt) :
0.0
SUM(dm_v_tr_duebill_mx.bal) :
0.0
SUM(dm_v_tr_duebill_mx.buss_amt) :
0.0
SUM(dm_v_tr_duebill_mx.buss_type) :
0.0
SUM(dm_v_tr_duebill_mx.dlay_amt) :
0.0
SUM(dm_v_tr_duebill_mx.dlay_days) :
0.0
SUM(dm_v_tr_duebill_mx.due_intr_days) :
0.0
SUM(dm_v_tr_duebill_mx.dull_amt) :
0.0
SUM(dm_v_tr_duebill_mx.fine_intr_int) :
0.0
SUM(dm_v_tr_duebill_mx.fine_pr_int) :
0.0
SUM(dm_v_tr_duebill_mx.loan_use) :
0.0
SUM(dm_v_tr_duebill_mx.norm_bal) :
0.0
SUM(dm_v_tr_duebill_mx.owed_int_in) :
0.0
SUM(dm_v_tr_duebill_mx.owed_int_out) :
0.0
SUM(dm_v_tr_duebill_mx.pay_freq) :
0.0
COUNT(dm_v_tr_huanb_mx) :
0.0
MAX(dm_v_tr_huanb_mx.bal) :
0.9501235128570348
deleted

MAX(dm_v_tr_huanb_mx.pay_term) :
0.9501235128570348
deleted

MAX(dm_v_tr_huanb_mx.pprd_amotz_intr) :
0.9501235128570348
deleted

MAX(dm_v_tr_huanb_mx.tran_amt) :
0.9501235128570348
deleted

MEAN(dm_v_tr_huanb_mx.bal) :
0.9501235128570348
deleted

MEAN(dm_v_tr_huanb_mx.pay_term) :
0.9501235128570348
deleted

MEAN(dm_v_tr_huanb_mx.pprd_amotz_intr) :
0.9501235128570348
deleted

MEAN(dm_v_tr_huanb_mx.tran_amt) :
0.9501235128570348
deleted

MIN(dm_v_tr_huanb_mx.bal) :
0.9501235128570348
deleted

MIN(dm_v_tr_huanb_mx.pay_term) :
0.9501235128570348
deleted

MIN(dm_v_tr_huanb_mx.pprd_amotz_intr) :
0.9501235128570348
deleted

MIN(dm_v_tr_huanb_mx.tran_amt) :
0.9501235128570348
deleted

MODE(dm_v_tr_huanb_mx.dr_cr_code) :
0.9501235128570348
deleted

MODE(dm_v_tr_huanb_mx.tran_type) :
0.9501235128570348
deleted

NUM_UNIQUE(dm_v_tr_huanb_mx.dr_cr_code) :
0.9501235128570348
deleted

NUM_UNIQUE(dm_v_tr_huanb_mx.tran_type) :
0.9501235128570348
deleted

SKEW(dm_v_tr_huanb_mx.bal) :
0.9686882865773521
deleted

SKEW(dm_v_tr_huanb_mx.pay_term) :
0.9686882865773521
deleted

SKEW(dm_v_tr_huanb_mx.pprd_amotz_intr) :
0.9686882865773521
deleted

SKEW(dm_v_tr_huanb_mx.tran_amt) :
0.9686882865773521
deleted

STD(dm_v_tr_huanb_mx.bal) :
0.9618692759187774
deleted

STD(dm_v_tr_huanb_mx.pay_term) :
0.9618692759187774
deleted

STD(dm_v_tr_huanb_mx.pprd_amotz_intr) :
0.9618692759187774
deleted

STD(dm_v_tr_huanb_mx.tran_amt) :
0.9618692759187774
deleted

SUM(dm_v_tr_huanb_mx.bal) :
0.0
SUM(dm_v_tr_huanb_mx.pay_term) :
0.0
SUM(dm_v_tr_huanb_mx.pprd_amotz_intr) :
0.0
SUM(dm_v_tr_huanb_mx.tran_amt) :
0.0
COUNT(dm_v_tr_huanx_mx) :
0.0
MAX(dm_v_tr_huanx_mx. cac_intc_pr) :
0.9473504943954751
deleted

MAX(dm_v_tr_huanx_mx.pay_term) :
0.9473504943954751
deleted

MAX(dm_v_tr_huanx_mx.tran_amt) :
0.9473504943954751
deleted

MEAN(dm_v_tr_huanx_mx. cac_intc_pr) :
0.9473504943954751
deleted

MEAN(dm_v_tr_huanx_mx.pay_term) :
0.9473504943954751
deleted

MEAN(dm_v_tr_huanx_mx.tran_amt) :
0.9473504943954751
deleted

MIN(dm_v_tr_huanx_mx. cac_intc_pr) :
0.9473504943954751
deleted

MIN(dm_v_tr_huanx_mx.pay_term) :
0.9473504943954751
deleted

MIN(dm_v_tr_huanx_mx.tran_amt) :
0.9473504943954751
deleted

MODE(dm_v_tr_huanx_mx. dr_cr_code) :
0.9473504943954751
deleted

MODE(dm_v_tr_huanx_mx. tran_flag) :
0.9473504943954751
deleted

NUM_UNIQUE(dm_v_tr_huanx_mx. dr_cr_code) :
0.9473504943954751
deleted

NUM_UNIQUE(dm_v_tr_huanx_mx. tran_flag) :
0.9473504943954751
deleted

SKEW(dm_v_tr_huanx_mx. cac_intc_pr) :
0.955452800198171
deleted

SKEW(dm_v_tr_huanx_mx.pay_term) :
0.955452800198171
deleted

SKEW(dm_v_tr_huanx_mx.tran_amt) :
0.955452800198171
deleted

STD(dm_v_tr_huanx_mx. cac_intc_pr) :
0.9516820455655788
deleted

STD(dm_v_tr_huanx_mx.pay_term) :
0.9516820455655788
deleted

STD(dm_v_tr_huanx_mx.tran_amt) :
0.9516820455655788
deleted

SUM(dm_v_tr_huanx_mx. cac_intc_pr) :
0.0
SUM(dm_v_tr_huanx_mx.pay_term) :
0.0
SUM(dm_v_tr_huanx_mx.tran_amt) :
0.0
COUNT(dm_v_tr_sa_mx) :
0.0
MAX(dm_v_tr_sa_mx. dr_amt) :
0.15002855589730887
MEAN(dm_v_tr_sa_mx. dr_amt) :
0.15002855589730887
MIN(dm_v_tr_sa_mx. dr_amt) :
0.15002855589730887
SKEW(dm_v_tr_sa_mx. dr_amt) :
0.16885136483427257
STD(dm_v_tr_sa_mx. dr_amt) :
0.15832352799510077
SUM(dm_v_tr_sa_mx. dr_amt) :
0.0
COUNT(pri_cust_asset_acct_info) :
0.0
MAX(pri_cust_asset_acct_info.avg_mth) :
0.44997901313571276
MAX(pri_cust_asset_acct_info.avg_qur) :
0.44997901313571276
MAX(pri_cust_asset_acct_info.avg_year) :
0.44997901313571276
MAX(pri_cust_asset_acct_info.bal) :
0.44997901313571276
MEAN(pri_cust_asset_acct_info.avg_mth) :
0.44997901313571276
MEAN(pri_cust_asset_acct_info.avg_qur) :
0.44997901313571276
MEAN(pri_cust_asset_acct_info.avg_year) :
0.44997901313571276
MEAN(pri_cust_asset_acct_info.bal) :
0.44997901313571276
MIN(pri_cust_asset_acct_info.avg_mth) :
0.44997901313571276
MIN(pri_cust_asset_acct_info.avg_qur) :
0.44997901313571276
MIN(pri_cust_asset_acct_info.avg_year) :
0.44997901313571276
MIN(pri_cust_asset_acct_info.bal) :
0.44997901313571276
MODE(pri_cust_asset_acct_info. acct_char) :
0.45009254863103715
MODE(pri_cust_asset_acct_info.acct_sts) :
0.4500856676919266
MODE(pri_cust_asset_acct_info.curr_type) :
0.44997901313571276
MODE(pri_cust_asset_acct_info.frz_sts) :
0.4500856676919266
MODE(pri_cust_asset_acct_info.is_secu_card) :
0.4500856676919266
MODE(pri_cust_asset_acct_info.prod_code) :
0.44997901313571276
MODE(pri_cust_asset_acct_info.stp_sts) :
0.4500856676919266
NUM_UNIQUE(pri_cust_asset_acct_info. acct_char) :
0.44997901313571276
NUM_UNIQUE(pri_cust_asset_acct_info.acct_sts) :
0.44997901313571276
NUM_UNIQUE(pri_cust_asset_acct_info.curr_type) :
0.44997901313571276
NUM_UNIQUE(pri_cust_asset_acct_info.frz_sts) :
0.44997901313571276
NUM_UNIQUE(pri_cust_asset_acct_info.is_secu_card) :
0.44997901313571276
NUM_UNIQUE(pri_cust_asset_acct_info.prod_code) :
0.44997901313571276
NUM_UNIQUE(pri_cust_asset_acct_info.stp_sts) :
0.44997901313571276
SKEW(pri_cust_asset_acct_info.avg_mth) :
0.9406243764148932

deleted

SKEW(pri_cust_asset_acct_info.avg_qur) :
0.9406243764148932
deleted

SKEW(pri_cust_asset_acct_info.avg_year) :
0.9406243764148932
deleted

SKEW(pri_cust_asset_acct_info.bal) :
0.9406243764148932
deleted

STD(pri_cust_asset_acct_info.avg_mth) :
0.8207618575783223
deleted

STD(pri_cust_asset_acct_info.avg_qur) :
0.8207618575783223
deleted

STD(pri_cust_asset_acct_info.avg_year) :
0.8207618575783223
deleted

STD(pri_cust_asset_acct_info.bal) :
0.8207618575783223
deleted

SUM(pri_cust_asset_acct_info.avg_mth) :
0.0
SUM(pri_cust_asset_acct_info.avg_qur) :
0.0
SUM(pri_cust_asset_acct_info.avg_year) :
0.0
SUM(pri_cust_asset_acct_info.bal) :
0.0
COUNT(pri_cust_asset_info) :
0.0
MAX(pri_cust_asset_info.acct_sts) :
5.504751288455848e-05
MAX(pri_cust_asset_info.book_acct_amt) :
5.504751288455848e-05
MAX(pri_cust_asset_info.defect_type) :
5.504751288455848e-05
MAX(pri_cust_asset_info.delay_bal) :
5.504751288455848e-05
MAX(pri_cust_asset_info.five_class) :
5.504751288455848e-05
MAX(pri_cust_asset_info.guar_amount) :
5.504751288455848e-05
MAX(pri_cust_asset_info.guar_eva_value) :
1.0
deleted

MAX(pri_cust_asset_info.is_extend) :
5.504751288455848e-05
MAX(pri_cust_asset_info.is_mortgage) :
5.504751288455848e-05
MAX(pri_cust_asset_info.is_online) :
5.504751288455848e-05
MAX(pri_cust_asset_info.loan_use) :
5.504751288455848e-05
MAX(pri_cust_asset_info.overdue_class) :
5.504751288455848e-05
MAX(pri_cust_asset_info.overdue_flag) :
5.504751288455848e-05
MAX(pri_cust_asset_info.owed_int_flag) :
5.504751288455848e-05
MAX(pri_cust_asset_info.owed_int_in) :
5.504751288455848e-05
MAX(pri_cust_asset_info.owed_int_out) :
5.504751288455848e-05
MAX(pri_cust_asset_info.pay_type) :
5.504751288455848e-05
MAX(pri_cust_asset_info.pro_char_ori) :
5.504751288455848e-05
MAX(pri_cust_asset_info.repay_type) :
5.504751288455848e-05
MAX(pri_cust_asset_info.vouch_type) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.acct_sts) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.book_acct_amt) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.defect_type) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.delay_bal) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.five_class) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.guar_amount) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.guar_eva_value) :
1.0
deleted

MEAN(pri_cust_asset_info.is_extend) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.is_mortgage) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.is_online) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.loan_use) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.overdue_class) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.overdue_flag) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.owed_int_flag) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.owed_int_in) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.owed_int_out) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.pay_type) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.pro_char_ori) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.repay_type) :
5.504751288455848e-05
MEAN(pri_cust_asset_info.vouch_type) :
5.504751288455848e-05
MIN(pri_cust_asset_info.acct_sts) :
5.504751288455848e-05
MIN(pri_cust_asset_info.book_acct_amt) :
5.504751288455848e-05
MIN(pri_cust_asset_info.defect_type) :
5.504751288455848e-05
MIN(pri_cust_asset_info.delay_bal) :
5.504751288455848e-05
MIN(pri_cust_asset_info.five_class) :
5.504751288455848e-05
MIN(pri_cust_asset_info.guar_amount) :
5.504751288455848e-05
MIN(pri_cust_asset_info.guar_eva_value) :
1.0
deleted

MIN(pri_cust_asset_info.is_extend) :
5.504751288455848e-05
MIN(pri_cust_asset_info.is_mortgage) :
5.504751288455848e-05
MIN(pri_cust_asset_info.is_online) :
5.504751288455848e-05
MIN(pri_cust_asset_info.loan_use) :
5.504751288455848e-05
MIN(pri_cust_asset_info.overdue_class) :
5.504751288455848e-05
MIN(pri_cust_asset_info.overdue_flag) :
5.504751288455848e-05
MIN(pri_cust_asset_info.owed_int_flag) :
5.504751288455848e-05
MIN(pri_cust_asset_info.owed_int_in) :
5.504751288455848e-05
MIN(pri_cust_asset_info.owed_int_out) :
5.504751288455848e-05
MIN(pri_cust_asset_info.pay_type) :
5.504751288455848e-05
MIN(pri_cust_asset_info.pro_char_ori) :
5.504751288455848e-05
MIN(pri_cust_asset_info.repay_type) :
5.504751288455848e-05
MIN(pri_cust_asset_info.vouch_type) :
5.504751288455848e-05
SKEW(pri_cust_asset_info.acct_sts) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.book_acct_amt) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.defect_type) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.delay_bal) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.five_class) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.guar_amount) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.guar_eva_value) :
1.0
deleted

SKEW(pri_cust_asset_info.is_extend) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.is_mortgage) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.is_online) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.loan_use) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.overdue_class) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.overdue_flag) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.owed_int_flag) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.owed_int_in) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.owed_int_out) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.pay_type) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.pro_char_ori) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.repay_type) :
0.9999896785913341
deleted

SKEW(pri_cust_asset_info.vouch_type) :
0.9999896785913341
deleted

STD(pri_cust_asset_info.acct_sts) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.book_acct_amt) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.defect_type) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.delay_bal) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.five_class) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.guar_amount) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.guar_eva_value) :
1.0
deleted

STD(pri_cust_asset_info.is_extend) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.is_mortgage) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.is_online) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.loan_use) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.overdue_class) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.overdue_flag) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.owed_int_flag) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.owed_int_in) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.owed_int_out) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.pay_type) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.pro_char_ori) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.repay_type) :
0.9978531469975023
deleted

STD(pri_cust_asset_info.vouch_type) :
0.9978531469975023
deleted

SUM(pri_cust_asset_info.acct_sts) :
0.0
SUM(pri_cust_asset_info.book_acct_amt) :
0.0
SUM(pri_cust_asset_info.defect_type) :
0.0
SUM(pri_cust_asset_info.delay_bal) :
0.0
SUM(pri_cust_asset_info.five_class) :
0.0
SUM(pri_cust_asset_info.guar_amount) :
0.0
SUM(pri_cust_asset_info.guar_eva_value) :
0.0
SUM(pri_cust_asset_info.is_extend) :
0.0
SUM(pri_cust_asset_info.is_mortgage) :
0.0
SUM(pri_cust_asset_info.is_online) :
0.0
SUM(pri_cust_asset_info.loan_use) :
0.0
SUM(pri_cust_asset_info.overdue_class) :
0.0
SUM(pri_cust_asset_info.overdue_flag) :
0.0
SUM(pri_cust_asset_info.owed_int_flag) :
0.0
SUM(pri_cust_asset_info.owed_int_in) :
0.0
SUM(pri_cust_asset_info.owed_int_out) :
0.0
SUM(pri_cust_asset_info.pay_type) :
0.0
SUM(pri_cust_asset_info.pro_char_ori) :
0.0
SUM(pri_cust_asset_info.repay_type) :
0.0
SUM(pri_cust_asset_info.vouch_type) :
0.0
COUNT(pri_cust_base_info) :
0.0
MODE(pri_cust_base_info.education) :
0.0
MODE(pri_cust_base_info.is_black) :
0.0
MODE(pri_cust_base_info.is_contact) :
0.0
MODE(pri_cust_base_info.is_employee) :
0.0
MODE(pri_cust_base_info.is_mgr_dep) :
0.0
MODE(pri_cust_base_info.is_shareholder) :
0.0
MODE(pri_cust_base_info.marrige) :
0.0
MODE(pri_cust_base_info.prof_titl) :
0.0
NUM_UNIQUE(pri_cust_base_info.education) :
0.0
NUM_UNIQUE(pri_cust_base_info.is_black) :
0.0
NUM_UNIQUE(pri_cust_base_info.is_contact) :
0.0
NUM_UNIQUE(pri_cust_base_info.is_employee) :
0.0
NUM_UNIQUE(pri_cust_base_info.is_mgr_dep) :
0.0
NUM_UNIQUE(pri_cust_base_info.is_shareholder) :
0.0
NUM_UNIQUE(pri_cust_base_info.marrige) :
0.0
NUM_UNIQUE(pri_cust_base_info.prof_titl) :
0.0
COUNT(pri_cust_liab_acct_info) :
0.0
MAX(pri_cust_liab_acct_info.acct_sts) :
0.9396851282263003

deleted

MAX(pri_cust_liab_acct_info.book_acct_amt) :
0.9466899242408604
deleted

MAX(pri_cust_liab_acct_info.delay_bal) :
0.9396851282263003
deleted

MAX(pri_cust_liab_acct_info.guar_amount) :
0.9396851282263003
deleted

MAX(pri_cust_liab_acct_info.guar_eva_value) :
0.9396851282263003
deleted

MAX(pri_cust_liab_acct_info.owed_int_in) :
0.9396851282263003
deleted

MAX(pri_cust_liab_acct_info.owed_int_out) :
0.9396851282263003
deleted

MEAN(pri_cust_liab_acct_info.acct_sts) :
0.9396851282263003
deleted

MEAN(pri_cust_liab_acct_info.book_acct_amt) :
0.9466899242408604
deleted

MEAN(pri_cust_liab_acct_info.delay_bal) :
0.9396851282263003
deleted

MEAN(pri_cust_liab_acct_info.guar_amount) :
0.9396851282263003
deleted

MEAN(pri_cust_liab_acct_info.guar_eva_value) :
0.9396851282263003
deleted

MEAN(pri_cust_liab_acct_info.owed_int_in) :
0.9396851282263003
deleted

MEAN(pri_cust_liab_acct_info.owed_int_out) :
0.9396851282263003
deleted

MIN(pri_cust_liab_acct_info.acct_sts) :
0.9396851282263003
deleted

MIN(pri_cust_liab_acct_info.book_acct_amt) :
0.9466899242408604
deleted

MIN(pri_cust_liab_acct_info.delay_bal) :
0.9396851282263003
deleted

MIN(pri_cust_liab_acct_info.guar_amount) :
0.9396851282263003
deleted

MIN(pri_cust_liab_acct_info.guar_eva_value) :
0.9396851282263003
deleted

MIN(pri_cust_liab_acct_info.owed_int_in) :
0.9396851282263003
deleted

MIN(pri_cust_liab_acct_info.owed_int_out) :
0.9396851282263003
deleted

MODE(pri_cust_liab_acct_info.defect_type) :
0.9396851282263003
deleted

MODE(pri_cust_liab_acct_info.five_class) :
0.9396851282263003
deleted

MODE(pri_cust_liab_acct_info.is_extend) :
0.9396851282263003
deleted

MODE(pri_cust_liab_acct_info.is_mortgage) :
0.9396851282263003
deleted

MODE(pri_cust_liab_acct_info.is_online) :
0.9396851282263003
deleted

MODE(pri_cust_liab_acct_info.loan_use) :
0.9396851282263003
deleted

MODE(pri_cust_liab_acct_info.overdue_class) :
0.9396851282263003
deleted

MODE(pri_cust_liab_acct_info.overdue_flag) :
0.9396851282263003
deleted

MODE(pri_cust_liab_acct_info.owed_int_flag) :
0.9396851282263003
deleted

MODE(pri_cust_liab_acct_info.pay_type) :
0.9396851282263003
deleted

MODE(pri_cust_liab_acct_info.pro_char_ori) :
0.9481314809845248
deleted

MODE(pri_cust_liab_acct_info.repay_type) :
0.9396851282263003
deleted

MODE(pri_cust_liab_acct_info.vouch_type) :
0.9396851282263003
deleted

NUM_UNIQUE(pri_cust_liab_acct_info.defect_type) :
0.9396851282263003
deleted

NUM_UNIQUE(pri_cust_liab_acct_info.five_class) :
0.9396851282263003
deleted

NUM_UNIQUE(pri_cust_liab_acct_info.is_extend) :
0.9396851282263003
deleted

NUM_UNIQUE(pri_cust_liab_acct_info.is_mortgage) :
0.9396851282263003
deleted

NUM_UNIQUE(pri_cust_liab_acct_info.is_online) :
0.9396851282263003
deleted

NUM_UNIQUE(pri_cust_liab_acct_info.loan_use) :
0.9396851282263003
deleted

NUM_UNIQUE(pri_cust_liab_acct_info.overdue_class) :
0.9396851282263003
deleted

NUM_UNIQUE(pri_cust_liab_acct_info.overdue_flag) :
0.9396851282263003
deleted

NUM_UNIQUE(pri_cust_liab_acct_info.owed_int_flag) :
0.9396851282263003
deleted

NUM_UNIQUE(pri_cust_liab_acct_info.pay_type) :
0.9396851282263003
deleted

NUM_UNIQUE(pri_cust_liab_acct_info.pro_char_ori) :
0.9396851282263003
deleted

NUM_UNIQUE(pri_cust_liab_acct_info.repay_type) :
0.9396851282263003
deleted

NUM_UNIQUE(pri_cust_liab_acct_info.vouch_type) :
0.9396851282263003
deleted

SKEW(pri_cust_liab_acct_info.acct_sts) :
0.9400394965904947
deleted

SKEW(pri_cust_liab_acct_info.book_acct_amt) :
0.9683752038478212
deleted

SKEW(pri_cust_liab_acct_info.delay_bal) :
0.9400394965904947
deleted

SKEW(pri_cust_liab_acct_info.guar_amount) :
0.9400394965904947
deleted

SKEW(pri_cust_liab_acct_info.guar_eva_value) :
0.9400394965904947
deleted

SKEW(pri_cust_liab_acct_info.owed_int_in) :
0.9400394965904947
deleted

SKEW(pri_cust_liab_acct_info.owed_int_out) :
0.9400394965904947
deleted

STD(pri_cust_liab_acct_info.acct_sts) :
0.9399294015647256
deleted

STD(pri_cust_liab_acct_info.book_acct_amt) :
0.9656606733687013
deleted

STD(pri_cust_liab_acct_info.delay_bal) :
0.9399294015647256
deleted

STD(pri_cust_liab_acct_info.guar_amount) :
0.9399294015647256
deleted

STD(pri_cust_liab_acct_info.guar_eva_value) :
0.9399294015647256
deleted

STD(pri_cust_liab_acct_info.owed_int_in) :
0.9399294015647256
deleted

STD(pri_cust_liab_acct_info.owed_int_out) :
0.9399294015647256
deleted

SUM(pri_cust_liab_acct_info.acct_sts) :
0.0
SUM(pri_cust_liab_acct_info.book_acct_amt) :
0.0
SUM(pri_cust_liab_acct_info.delay_bal) :
0.0
SUM(pri_cust_liab_acct_info.guar_amount) :
0.0
SUM(pri_cust_liab_acct_info.guar_eva_value) :
0.0
SUM(pri_cust_liab_acct_info.owed_int_in) :
0.0
SUM(pri_cust_liab_acct_info.owed_int_out) :
0.0
COUNT(dm_v_tr_etc_mx) :
0.0
MAX(dm_v_tr_etc_mx. tran_amt_fen) :
0.9729854330519029
deleted

MEAN(dm_v_tr_etc_mx. tran_amt_fen) :
0.9729854330519029
deleted

MIN(dm_v_tr_etc_mx. tran_amt_fen) :
0.9729854330519029
deleted

SKEW(dm_v_tr_etc_mx. tran_amt_fen) :
0.9758203799654577
deleted

STD(dm_v_tr_etc_mx. tran_amt_fen) :
0.9741242284747023
deleted

SUM(dm_v_tr_etc_mx. tran_amt_fen) :
0.0
COUNT(dm_v_tr_gzdf_mx) :
0.0
MAX(dm_v_tr_gzdf_mx. is_secu_card) :
0.665101253019012
MAX(dm_v_tr_gzdf_mx. tran_amt) :
0.665101253019012
MEAN(dm_v_tr_gzdf_mx. is_secu_card) :
0.665101253019012
MEAN(dm_v_tr_gzdf_mx. tran_amt) :
0.665101253019012
MIN(dm_v_tr_gzdf_mx. is_secu_card) :
0.665101253019012
MIN(dm_v_tr_gzdf_mx. tran_amt) :
0.665101253019012
SKEW(dm_v_tr_gzdf_mx. is_secu_card) :
0.8047155075724735
deleted

SKEW(dm_v_tr_gzdf_mx. tran_amt) :
0.8047155075724735
deleted

STD(dm_v_tr_gzdf_mx. is_secu_card) :
0.7462584893586277
deleted

STD(dm_v_tr_gzdf_mx. tran_amt) :
0.7462584893586277
deleted

SUM(dm_v_tr_gzdf_mx. is_secu_card) :
0.0
SUM(dm_v_tr_gzdf_mx. tran_amt) :
0.0
COUNT(dm_v_tr_sbyb_mx) :
0.0
MODE(dm_v_tr_sbyb_mx. tran_sts) :
0.628209097977692
NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts) :
0.628209097977692
COUNT(dm_v_tr_sdrq_mx) :
0.0
MODE(dm_v_tr_sdrq_mx. tran_sts) :
0.9154366988006523
deleted

NUM_UNIQUE(dm_v_tr_sdrq_mx. tran_sts) :
0.9154366988006523
deleted

COUNT(dm_v_tr_sjyh_mx) :
0.0
MAX(dm_v_tr_sjyh_mx. tran_amt) :
0.8957572129444227
deleted

MEAN(dm_v_tr_sjyh_mx. tran_amt) :
0.8957572129444227
deleted

MIN(dm_v_tr_sjyh_mx. tran_amt) :
0.8957572129444227
deleted

MODE(dm_v_tr_sjyh_mx. tran_sts) :
0.8957572129444227
deleted

NUM_UNIQUE(dm_v_tr_sjyh_mx. tran_sts) :
0.8957572129444227
deleted

SKEW(dm_v_tr_sjyh_mx. tran_amt) :
0.930757109730336
deleted

STD(dm_v_tr_sjyh_mx. tran_amt) :
0.9180067295584501
deleted

SUM(dm_v_tr_sjyh_mx. tran_amt) :
0.0
COUNT(pri_cust_liab_info) :
0.0
MAX(pri_cust_liab_info.all_bal) :
0.9430946335555876
deleted

MAX(pri_cust_liab_info.bad_bal) :
0.9430946335555876
deleted

MAX(pri_cust_liab_info.delay_bal) :
0.9430946335555876
deleted

MAX(pri_cust_liab_info.due_intr) :
0.9430946335555876
deleted

MEAN(pri_cust_liab_info.all_bal) :
0.9430946335555876
deleted

MEAN(pri_cust_liab_info.bad_bal) :
0.9430946335555876
deleted

MEAN(pri_cust_liab_info.delay_bal) :
0.9430946335555876
deleted

MEAN(pri_cust_liab_info.due_intr) :
0.9430946335555876
deleted

MIN(pri_cust_liab_info.all_bal) :
0.9430946335555876
deleted

MIN(pri_cust_liab_info.bad_bal) :
0.9430946335555876
deleted

MIN(pri_cust_liab_info.delay_bal) :
0.9430946335555876
deleted

MIN(pri_cust_liab_info.due_intr) :
0.9430946335555876
deleted

SKEW(pri_cust_liab_info.all_bal) :
0.9434421209806715
deleted

SKEW(pri_cust_liab_info.bad_bal) :
0.9434421209806715
deleted

SKEW(pri_cust_liab_info.delay_bal) :
0.9434421209806715
deleted

SKEW(pri_cust_liab_info.due_intr) :
0.9434421209806715
deleted

STD(pri_cust_liab_info.all_bal) :
0.9432907403202389
deleted

STD(pri_cust_liab_info.bad_bal) :
0.9432907403202389
deleted

STD(pri_cust_liab_info.delay_bal) :
0.9432907403202389
deleted

STD(pri_cust_liab_info.due_intr) :
0.9432907403202389
deleted

SUM(pri_cust_liab_info.all_bal) :
0.0
SUM(pri_cust_liab_info.bad_bal) :
0.0
SUM(pri_cust_liab_info.delay_bal) :
0.0
SUM(pri_cust_liab_info.due_intr) :
0.0
COUNT(v_tr_shop_mx) :
0.0
MAX(v_tr_shop_mx. current_status) :
0.9694589517577359
deleted

MAX(v_tr_shop_mx. tran_sts) :
0.9694589517577359
deleted

MEAN(v_tr_shop_mx. current_status) :
0.9694589517577359
deleted

MEAN(v_tr_shop_mx. tran_sts) :
0.9694589517577359

deleted

MIN(v_tr_shop_mx. current_status) :
0.9694589517577359
deleted

MIN(v_tr_shop_mx. tran_sts) :
0.9694589517577359
deleted

SKEW(v_tr_shop_mx. current_status) :
0.9733501228247631
deleted

SKEW(v_tr_shop_mx. tran_sts) :
0.9733501228247631
deleted

STD(v_tr_shop_mx. current_status) :
0.9717640663597767
deleted

STD(v_tr_shop_mx. tran_sts) :
0.9717640663597767
deleted

SUM(v_tr_shop_mx. current_status) :
0.0
SUM(v_tr_shop_mx. tran_sts) :
0.0
COUNT(pri_credit_info) :
0.0
MAX(pri_credit_info.credit_level) :
0.8805503375100634
deleted

MEAN(pri_credit_info.credit_level) :
0.8805503375100634
deleted

MIN(pri_credit_info.credit_level) :
0.8805503375100634
deleted

SKEW(pri_credit_info.credit_level) :
1.0
deleted

STD(pri_credit_info.credit_level) :
1.0
deleted

SUM(pri_credit_info.credit_level) :
0.0

In [6]:
for column in df.columns.to_list():
    zero_count = len(df[df[column] == 0])
    print('%s, 零值：%d' % (column, zero_count))
    missing_percent = zero_count / 290658
    if(missing_percent > 0.7):
        df.drop(column,axis=1,inplace=True)
        print("deleted\n")

uid, 零值：0
 star_level, 零值：0
COUNT(dm_v_as_djk_info), 零值：275589
deleted

SUM(dm_v_as_djk_info.bal), 零值：290658
deleted

SUM(dm_v_as_djk_info.cred_limit), 零值：275640
deleted

SUM(dm_v_as_djk_info.deposit), 零值：288935
deleted

SUM(dm_v_as_djk_info.dlay_amt), 零值：290104
deleted

SUM(dm_v_as_djk_info.five_class), 零值：275589
deleted

SUM(dm_v_as_djk_info.over_draft), 零值：285903
deleted

COUNT(dm_v_as_djkfq_info), 零值：290311
deleted

SUM(dm_v_as_djkfq_info.instl_cnt), 零值：290316
deleted

SUM(dm_v_as_djkfq_info.mp_number), 零值：290311
deleted

SUM(dm_v_as_djkfq_info.mp_number.1), 零值：290311
deleted

SUM(dm_v_as_djkfq_info.rec_fee), 零值：290316
deleted

SUM(dm_v_as_djkfq_info.rem_fee), 零值：290526
deleted

SUM(dm_v_as_djkfq_info.total_amt), 零值：290311
deleted

SUM(dm_v_as_djkfq_info.total_mths), 零值：290311
deleted

COUNT(dm_v_tr_contract_mx), 零值：250343
deleted

SUM(dm_v_tr_contract_mx.buss_amt), 零值：250376
deleted

SUM(dm_v_tr_contract_mx.dlay_days), 零值：290658
deleted

SUM(dm_v_tr_contract_mx.due_intr_days), 零值：290658
deleted

SUM(dm_v_tr_contract_mx.fine_intr_int), 零值：289739
deleted

SUM(dm_v_tr_contract_mx.fine_pr_int), 零值：285999
deleted

SUM(dm_v_tr_contract_mx.frz_amt), 零值：290533
deleted

SUM(dm_v_tr_contract_mx.is_bad), 零值：290658
deleted

SUM(dm_v_tr_contract_mx.loan_pert), 零值：287237
deleted

SUM(dm_v_tr_contract_mx.owed_int_in), 零值：290434
deleted

SUM(dm_v_tr_contract_mx.owed_int_out), 零值：289022
deleted

SUM(dm_v_tr_contract_mx.pay_times), 零值：289859
deleted

SUM(dm_v_tr_contract_mx.term_day), 零值：290658
deleted

SUM(dm_v_tr_contract_mx.term_mth), 零值：250455
deleted

SUM(dm_v_tr_contract_mx.term_year), 零值：290658
deleted

COUNT(dm_v_tr_djk_mx), 零值：281677
deleted

SUM(dm_v_tr_djk_mx.tran_amt), 零值：281677
deleted

SUM(dm_v_tr_djk_mx.tran_type), 零值：281677
deleted

COUNT(dm_v_tr_dsf_mx), 零值：289090
deleted

SUM(dm_v_tr_dsf_mx.tran_amt), 零值：289090
deleted

COUNT(dm_v_tr_duebill_mx), 零值：266147
deleted

SUM(dm_v_tr_duebill_mx.bad_debt_amt), 零值：290658
deleted

SUM(dm_v_tr_duebill_mx.bal), 零值：277637
deleted

SUM(dm_v_tr_duebill_mx.buss_amt), 零值：266147
deleted

SUM(dm_v_tr_duebill_mx.buss_type), 零值：266148
deleted

SUM(dm_v_tr_duebill_mx.dlay_amt), 零值：290476
deleted

SUM(dm_v_tr_duebill_mx.dlay_days), 零值：290658
deleted

SUM(dm_v_tr_duebill_mx.due_intr_days), 零值：290658
deleted

SUM(dm_v_tr_duebill_mx.dull_amt), 零值：289324
deleted

SUM(dm_v_tr_duebill_mx.fine_intr_int), 零值：289739
deleted

SUM(dm_v_tr_duebill_mx.fine_pr_int), 零值：285999
deleted

SUM(dm_v_tr_duebill_mx.loan_use), 零值：290658
deleted

SUM(dm_v_tr_duebill_mx.norm_bal), 零值：279067
deleted

SUM(dm_v_tr_duebill_mx.owed_int_in), 零值：290434
deleted

SUM(dm_v_tr_duebill_mx.owed_int_out), 零值：289022
deleted

SUM(dm_v_tr_duebill_mx.pay_freq), 零值：266147
deleted

COUNT(dm_v_tr_huanb_mx), 零值：276161
deleted

SUM(dm_v_tr_huanb_mx.bal), 零值：281476
deleted

SUM(dm_v_tr_huanb_mx.pay_term), 零值：276511
deleted

SUM(dm_v_tr_huanb_mx.pprd_amotz_intr), 零值：276679
deleted

SUM(dm_v_tr_huanb_mx.tran_amt), 零值：276161
deleted

COUNT(dm_v_tr_huanx_mx), 零值：275355
deleted

SUM(dm_v_tr_huanx_mx. cac_intc_pr), 零值：275382
deleted

SUM(dm_v_tr_huanx_mx.pay_term), 零值：275364
deleted

SUM(dm_v_tr_huanx_mx.tran_amt), 零值：275355
deleted

COUNT(dm_v_tr_sa_mx), 零值：43607
MAX(dm_v_tr_sa_mx. dr_amt), 零值：29582
MEAN(dm_v_tr_sa_mx. dr_amt), 零值：29592
MIN(dm_v_tr_sa_mx. dr_amt), 零值：233147
deleted

SKEW(dm_v_tr_sa_mx. dr_amt), 零值：27738
STD(dm_v_tr_sa_mx. dr_amt), 零值：28324
SUM(dm_v_tr_sa_mx. dr_amt), 零值：73199
COUNT(pri_cust_asset_acct_info), 零值：130790
MAX(pri_cust_asset_acct_info.avg_mth), 零值：31247
MAX(pri_cust_asset_acct_info.avg_qur), 零值：159868
MAX(pri_cust_asset_acct_info.avg_year), 零值：26315
MAX(pri_cust_asset_acct_info.bal), 零值：27849
MEAN(pri_cust_asset_acct_info.avg_mth), 零值：31247
MEAN(pri_cust_asset_acct_info.avg_qur), 零值：159868
MEAN(pri_cust_asset_acct_info.avg_year), 零值：26315
MEAN(pri_cust_asset_acct_info.bal), 零值：27849
MIN(pri_cust_asset_acct_info.avg_mth), 零值：58791
MIN(pri_cust_asset_acct_info.avg_qur), 零值：159868
MIN(pri_cust_asset_acct_info.avg_year), 零值：51554
MIN(pri_cust_asset_acct_info.bal), 零值：53278
MODE(pri_cust_asset_acct_info. acct_char), 零值：0
MODE(pri_cust_asset_acct_info.acct_sts), 零值：0
MODE(pri_cust_asset_acct_info.curr_type), 零值：0
MODE(pri_cust_asset_acct_info.frz_sts), 零值：0
MODE(pri_cust_asset_acct_info.is_secu_card), 零值：0
MODE(pri_cust_asset_acct_info.prod_code), 零值：0
MODE(pri_cust_asset_acct_info.stp_sts), 零值：0
NUM_UNIQUE(pri_cust_asset_acct_info. acct_char), 零值：33
NUM_UNIQUE(pri_cust_asset_acct_info.acct_sts), 零值：31
NUM_UNIQUE(pri_cust_asset_acct_info.curr_type), 零值：0
NUM_UNIQUE(pri_cust_asset_acct_info.frz_sts), 零值：31
NUM_UNIQUE(pri_cust_asset_acct_info.is_secu_card), 零值：31
NUM_UNIQUE(pri_cust_asset_acct_info.prod_code), 零值：0
NUM_UNIQUE(pri_cust_asset_acct_info.stp_sts), 零值：31
SUM(pri_cust_asset_acct_info.avg_mth), 零值：162037
SUM(pri_cust_asset_acct_info.avg_qur), 零值：290658
deleted

SUM(pri_cust_asset_acct_info.avg_year), 零值：157105
SUM(pri_cust_asset_acct_info.bal), 零值：158639
COUNT(pri_cust_asset_info), 零值：16
MAX(pri_cust_asset_info.acct_sts), 零值：280055
deleted

MAX(pri_cust_asset_info.book_acct_amt), 零值：246991
deleted

MAX(pri_cust_asset_info.defect_type), 零值：290358
deleted

MAX(pri_cust_asset_info.delay_bal), 零值：248678
deleted

MAX(pri_cust_asset_info.five_class), 零值：217258
deleted

MAX(pri_cust_asset_info.guar_amount), 零值：287482
deleted

MAX(pri_cust_asset_info.is_extend), 零值：24688
MAX(pri_cust_asset_info.is_mortgage), 零值：29907
MAX(pri_cust_asset_info.is_online), 零值：290642
deleted

MAX(pri_cust_asset_info.loan_use), 零值：288487
deleted

MAX(pri_cust_asset_info.overdue_class), 零值：289767
deleted

MAX(pri_cust_asset_info.overdue_flag), 零值：42594
MAX(pri_cust_asset_info.owed_int_flag), 零值：290642
deleted

MAX(pri_cust_asset_info.owed_int_in), 零值：288952
deleted

MAX(pri_cust_asset_info.owed_int_out), 零值：288723
deleted

MAX(pri_cust_asset_info.pay_type), 零值：290642
deleted

MAX(pri_cust_asset_info.pro_char_ori), 零值：287784
deleted

MAX(pri_cust_asset_info.repay_type), 零值：33192
MAX(pri_cust_asset_info.vouch_type), 零值：27424
MEAN(pri_cust_asset_info.acct_sts), 零值：280055
deleted

MEAN(pri_cust_asset_info.book_acct_amt), 零值：246991
deleted

MEAN(pri_cust_asset_info.defect_type), 零值：290358
deleted

MEAN(pri_cust_asset_info.delay_bal), 零值：248678
deleted

MEAN(pri_cust_asset_info.five_class), 零值：217258
deleted

MEAN(pri_cust_asset_info.guar_amount), 零值：287482
deleted

MEAN(pri_cust_asset_info.is_extend), 零值：24688
MEAN(pri_cust_asset_info.is_mortgage), 零值：29907
MEAN(pri_cust_asset_info.is_online), 零值：290642
deleted

MEAN(pri_cust_asset_info.loan_use), 零值：288487
deleted

MEAN(pri_cust_asset_info.overdue_class), 零值：289767
deleted

MEAN(pri_cust_asset_info.overdue_flag), 零值：42594
MEAN(pri_cust_asset_info.owed_int_flag), 零值：290642
deleted

MEAN(pri_cust_asset_info.owed_int_in), 零值：288952
deleted

MEAN(pri_cust_asset_info.owed_int_out), 零值：288723
deleted

MEAN(pri_cust_asset_info.pay_type), 零值：290642
deleted

MEAN(pri_cust_asset_info.pro_char_ori), 零值：287784
deleted

MEAN(pri_cust_asset_info.repay_type), 零值：33192
MEAN(pri_cust_asset_info.vouch_type), 零值：27424
MIN(pri_cust_asset_info.acct_sts), 零值：280089
deleted

MIN(pri_cust_asset_info.book_acct_amt), 零值：247115
deleted

MIN(pri_cust_asset_info.defect_type), 零值：290362
deleted

MIN(pri_cust_asset_info.delay_bal), 零值：248795
deleted

MIN(pri_cust_asset_info.five_class), 零值：217465
deleted

MIN(pri_cust_asset_info.guar_amount), 零值：287487
deleted

MIN(pri_cust_asset_info.is_extend), 零值：24856
MIN(pri_cust_asset_info.is_mortgage), 零值：30091
MIN(pri_cust_asset_info.is_online), 零值：290642
deleted

MIN(pri_cust_asset_info.loan_use), 零值：288499
deleted

MIN(pri_cust_asset_info.overdue_class), 零值：289769
deleted

MIN(pri_cust_asset_info.overdue_flag), 零值：43183
MIN(pri_cust_asset_info.owed_int_flag), 零值：290642
deleted

MIN(pri_cust_asset_info.owed_int_in), 零值：288959
deleted

MIN(pri_cust_asset_info.owed_int_out), 零值：288725
deleted

MIN(pri_cust_asset_info.pay_type), 零值：290642
deleted

MIN(pri_cust_asset_info.pro_char_ori), 零值：287792
deleted

MIN(pri_cust_asset_info.repay_type), 零值：33378
MIN(pri_cust_asset_info.vouch_type), 零值：27592
SUM(pri_cust_asset_info.acct_sts), 零值：280071
deleted

SUM(pri_cust_asset_info.book_acct_amt), 零值：247007
deleted

SUM(pri_cust_asset_info.defect_type), 零值：290374
deleted

SUM(pri_cust_asset_info.delay_bal), 零值：248694
deleted

SUM(pri_cust_asset_info.five_class), 零值：217274
deleted

SUM(pri_cust_asset_info.guar_amount), 零值：287498
deleted

SUM(pri_cust_asset_info.guar_eva_value), 零值：290658
deleted

SUM(pri_cust_asset_info.is_extend), 零值：24704
SUM(pri_cust_asset_info.is_mortgage), 零值：29923
SUM(pri_cust_asset_info.is_online), 零值：290658
deleted

SUM(pri_cust_asset_info.loan_use), 零值：288503
deleted

SUM(pri_cust_asset_info.overdue_class), 零值：289783
deleted

SUM(pri_cust_asset_info.overdue_flag), 零值：42610
SUM(pri_cust_asset_info.owed_int_flag), 零值：290658
deleted

SUM(pri_cust_asset_info.owed_int_in), 零值：288968
deleted

SUM(pri_cust_asset_info.owed_int_out), 零值：288739
deleted

SUM(pri_cust_asset_info.pay_type), 零值：290658
deleted

SUM(pri_cust_asset_info.pro_char_ori), 零值：287800
deleted

SUM(pri_cust_asset_info.repay_type), 零值：33208
SUM(pri_cust_asset_info.vouch_type), 零值：27440
COUNT(pri_cust_base_info), 零值：0
MODE(pri_cust_base_info.education), 零值：0
MODE(pri_cust_base_info.is_black), 零值：0
MODE(pri_cust_base_info.is_contact), 零值：0
MODE(pri_cust_base_info.is_employee), 零值：0
MODE(pri_cust_base_info.is_mgr_dep), 零值：0
MODE(pri_cust_base_info.is_shareholder), 零值：0
MODE(pri_cust_base_info.marrige), 零值：0
MODE(pri_cust_base_info.prof_titl), 零值：0
NUM_UNIQUE(pri_cust_base_info.education), 零值：0
NUM_UNIQUE(pri_cust_base_info.is_black), 零值：0
NUM_UNIQUE(pri_cust_base_info.is_contact), 零值：0
NUM_UNIQUE(pri_cust_base_info.is_employee), 零值：0
NUM_UNIQUE(pri_cust_base_info.is_mgr_dep), 零值：0
NUM_UNIQUE(pri_cust_base_info.is_shareholder), 零值：0
NUM_UNIQUE(pri_cust_base_info.marrige), 零值：0
NUM_UNIQUE(pri_cust_base_info.prof_titl), 零值：0
COUNT(pri_cust_liab_acct_info), 零值：273127
deleted

SUM(pri_cust_liab_acct_info.acct_sts), 零值：273127
deleted

SUM(pri_cust_liab_acct_info.book_acct_amt), 零值：282506
deleted

SUM(pri_cust_liab_acct_info.delay_bal), 零值：288136
deleted

SUM(pri_cust_liab_acct_info.guar_amount), 零值：287159
deleted

SUM(pri_cust_liab_acct_info.guar_eva_value), 零值：286897
deleted

SUM(pri_cust_liab_acct_info.owed_int_in), 零值：287810
deleted

SUM(pri_cust_liab_acct_info.owed_int_out), 零值：288339
deleted

COUNT(dm_v_tr_etc_mx), 零值：282806
deleted

SUM(dm_v_tr_etc_mx. tran_amt_fen), 零值：282806
deleted

COUNT(dm_v_tr_gzdf_mx), 零值：193317
MAX(dm_v_tr_gzdf_mx. is_secu_card), 零值：10906
MAX(dm_v_tr_gzdf_mx. tran_amt), 零值：0
MEAN(dm_v_tr_gzdf_mx. is_secu_card), 零值：10906
MEAN(dm_v_tr_gzdf_mx. tran_amt), 零值：0
MIN(dm_v_tr_gzdf_mx. is_secu_card), 零值：12573
MIN(dm_v_tr_gzdf_mx. tran_amt), 零值：9
SUM(dm_v_tr_gzdf_mx. is_secu_card), 零值：204223
deleted

SUM(dm_v_tr_gzdf_mx. tran_amt), 零值：193317
COUNT(dm_v_tr_sbyb_mx), 零值：182594
MODE(dm_v_tr_sbyb_mx. tran_sts), 零值：0
NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts), 零值：0
COUNT(dm_v_tr_sdrq_mx), 零值：266079
deleted

COUNT(dm_v_tr_sjyh_mx), 零值：260359
deleted

SUM(dm_v_tr_sjyh_mx. tran_amt), 零值：260359
deleted

COUNT(pri_cust_liab_info), 零值：274118
deleted

SUM(pri_cust_liab_info.all_bal), 零值：274465
deleted

SUM(pri_cust_liab_info.bad_bal), 零值：288808
deleted

SUM(pri_cust_liab_info.delay_bal), 零值：288687
deleted

SUM(pri_cust_liab_info.due_intr), 零值：287723
deleted

COUNT(v_tr_shop_mx), 零值：281781
deleted

SUM(v_tr_shop_mx. current_status), 零值：281781
deleted

SUM(v_tr_shop_mx. tran_sts), 零值：281781
deleted

COUNT(pri_credit_info), 零值：255939
deleted

SUM(pri_credit_info.credit_level), 零值：255939
deleted

In [7]:
for column in df.columns.to_list():
    print(column)
    zero_count = len(df[df[column] == 0])
    null_count = df[column].isnull().sum()
    missing_count = zero_count + null_count
    missing_percent = missing_count / 290658
    if(missing_percent > 0.7):
        df.drop(column,axis=1,inplace=True)
        print("deleted\n")

uid
 star_level
COUNT(dm_v_tr_sa_mx)
MAX(dm_v_tr_sa_mx. dr_amt)
MEAN(dm_v_tr_sa_mx. dr_amt)
SKEW(dm_v_tr_sa_mx. dr_amt)
STD(dm_v_tr_sa_mx. dr_amt)
SUM(dm_v_tr_sa_mx. dr_amt)
COUNT(pri_cust_asset_acct_info)
MAX(pri_cust_asset_acct_info.avg_mth)
MAX(pri_cust_asset_acct_info.avg_qur)
deleted

MAX(pri_cust_asset_acct_info.avg_year)
MAX(pri_cust_asset_acct_info.bal)
MEAN(pri_cust_asset_acct_info.avg_mth)
MEAN(pri_cust_asset_acct_info.avg_qur)
deleted

MEAN(pri_cust_asset_acct_info.avg_year)
MEAN(pri_cust_asset_acct_info.bal)
MIN(pri_cust_asset_acct_info.avg_mth)
MIN(pri_cust_asset_acct_info.avg_qur)
deleted

MIN(pri_cust_asset_acct_info.avg_year)
MIN(pri_cust_asset_acct_info.bal)
MODE(pri_cust_asset_acct_info. acct_char)
MODE(pri_cust_asset_acct_info.acct_sts)
MODE(pri_cust_asset_acct_info.curr_type)
MODE(pri_cust_asset_acct_info.frz_sts)
MODE(pri_cust_asset_acct_info.is_secu_card)
MODE(pri_cust_asset_acct_info.prod_code)
MODE(pri_cust_asset_acct_info.stp_sts)
NUM_UNIQUE(pri_cust_asset_acct_info. acct_char)
NUM_UNIQUE(pri_cust_asset_acct_info.acct_sts)
NUM_UNIQUE(pri_cust_asset_acct_info.curr_type)
NUM_UNIQUE(pri_cust_asset_acct_info.frz_sts)
NUM_UNIQUE(pri_cust_asset_acct_info.is_secu_card)
NUM_UNIQUE(pri_cust_asset_acct_info.prod_code)
NUM_UNIQUE(pri_cust_asset_acct_info.stp_sts)
SUM(pri_cust_asset_acct_info.avg_mth)
SUM(pri_cust_asset_acct_info.avg_year)
SUM(pri_cust_asset_acct_info.bal)
COUNT(pri_cust_asset_info)
MAX(pri_cust_asset_info.is_extend)
MAX(pri_cust_asset_info.is_mortgage)
MAX(pri_cust_asset_info.overdue_flag)
MAX(pri_cust_asset_info.repay_type)
MAX(pri_cust_asset_info.vouch_type)
MEAN(pri_cust_asset_info.is_extend)
MEAN(pri_cust_asset_info.is_mortgage)
MEAN(pri_cust_asset_info.overdue_flag)
MEAN(pri_cust_asset_info.repay_type)
MEAN(pri_cust_asset_info.vouch_type)
MIN(pri_cust_asset_info.is_extend)
MIN(pri_cust_asset_info.is_mortgage)
MIN(pri_cust_asset_info.overdue_flag)
MIN(pri_cust_asset_info.repay_type)
MIN(pri_cust_asset_info.vouch_type)
SUM(pri_cust_asset_info.is_extend)
SUM(pri_cust_asset_info.is_mortgage)
SUM(pri_cust_asset_info.overdue_flag)
SUM(pri_cust_asset_info.repay_type)
SUM(pri_cust_asset_info.vouch_type)
COUNT(pri_cust_base_info)
MODE(pri_cust_base_info.education)
MODE(pri_cust_base_info.is_black)
MODE(pri_cust_base_info.is_contact)
MODE(pri_cust_base_info.is_employee)
MODE(pri_cust_base_info.is_mgr_dep)
MODE(pri_cust_base_info.is_shareholder)
MODE(pri_cust_base_info.marrige)
MODE(pri_cust_base_info.prof_titl)
NUM_UNIQUE(pri_cust_base_info.education)
NUM_UNIQUE(pri_cust_base_info.is_black)
NUM_UNIQUE(pri_cust_base_info.is_contact)
NUM_UNIQUE(pri_cust_base_info.is_employee)
NUM_UNIQUE(pri_cust_base_info.is_mgr_dep)
NUM_UNIQUE(pri_cust_base_info.is_shareholder)
NUM_UNIQUE(pri_cust_base_info.marrige)
NUM_UNIQUE(pri_cust_base_info.prof_titl)
COUNT(dm_v_tr_gzdf_mx)
MAX(dm_v_tr_gzdf_mx. is_secu_card)
deleted

MAX(dm_v_tr_gzdf_mx. tran_amt)
MEAN(dm_v_tr_gzdf_mx. is_secu_card)
deleted

MEAN(dm_v_tr_gzdf_mx. tran_amt)
MIN(dm_v_tr_gzdf_mx. is_secu_card)
deleted

MIN(dm_v_tr_gzdf_mx. tran_amt)
SUM(dm_v_tr_gzdf_mx. tran_amt)
COUNT(dm_v_tr_sbyb_mx)
MODE(dm_v_tr_sbyb_mx. tran_sts)
NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)

In [8]:
df

,uid,star_level,COUNT(dm_v_tr_sa_mx),MAX(dm_v_tr_sa_mx. dr_amt),MEAN(dm_v_tr_sa_mx. dr_amt),SKEW(dm_v_tr_sa_mx. dr_amt),STD(dm_v_tr_sa_mx. dr_amt),SUM(dm_v_tr_sa_mx. dr_amt),COUNT(pri_cust_asset_acct_info),MAX(pri_cust_asset_acct_info.avg_mth),...,NUM_UNIQUE(pri_cust_base_info.marrige),NUM_UNIQUE(pri_cust_base_info.prof_titl),COUNT(dm_v_tr_gzdf_mx),MAX(dm_v_tr_gzdf_mx. tran_amt),MEAN(dm_v_tr_gzdf_mx. tran_amt),MIN(dm_v_tr_gzdf_mx. tran_amt),SUM(dm_v_tr_gzdf_mx. tran_amt),COUNT(dm_v_tr_sbyb_mx),MODE(dm_v_tr_sbyb_mx. tran_sts),NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)
0,130581199112042682,1,0.0,NaN,NaN,NaN,NaN,0.00,0.0,NaN,...,1,1,0.0,NaN,NaN,NaN,0.00,0.0,NaN,NaN
1,130635198511165690,3,322.0,100000.0,764.585093,16.866106,5666.331648,246196.40,0.0,NaN,...,1,1,14.0,13000.0,4022.707857,108.0,56317.91,0.0,NaN,NaN
2,130684198606215045,1,61.0,50000.0,3336.375410,3.939888,10650.924472,203518.90,0.0,NaN,...,1,1,0.0,NaN,NaN,NaN,0.00,0.0,NaN,NaN
3,130802201408149594,1,0.0,NaN,NaN,NaN,NaN,0.00,0.0,NaN,...,1,1,0.0,NaN,NaN,NaN,0.00,0.0,NaN,NaN
4,140902198607183528,1,4.0,0.0,0.000000,0.000000,0.000000,0.00,1.0,9.80,...,1,1,0.0,NaN,NaN,NaN,0.00,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290653,654324198006010321,1,12.0,18000.0,3772.039167,1.607053,6181.982161,45264.47,0.0,NaN,...,1,1,1.0,4410.0,4410.000000,4410.0,4410.00,0.0,NaN,NaN
290654,654326198608203393,2,336.0,300000.0,1966.526815,12.891771,22734.398727,660753.01,0.0,NaN,...,1,1,2.0,7500.0,6250.000000,5000.0,12500.00,0.0,NaN,NaN
290655,810000200811269255,1,9.0,0.0,0.000000,0.000000,0.000000,0.00,0.0,NaN,...,1,1,3.0,117.0,52.333333,20.0,157.00,0.0,NaN,NaN
290656,830000197007029225,1,7.0,690.0,154.285714,1.623706,277.360003,1080.00,1.0,60.92,...,1,1,0.0,NaN,NaN,NaN,0.00,1.0,S,1.0
290657,830000200706189396,-1,6.0,0.0,0.000000,0.000000,0.000000,0.00,0.0,NaN,...,1,1,1.0,260.0,260.000000,260.0,260.00,0.0,NaN,NaN

In [9]:
df.to_csv("./star_blank.csv")

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./star_blank.csv")
df

,Unnamed: 0,uid,star_level,COUNT(dm_v_tr_sa_mx),MAX(dm_v_tr_sa_mx. dr_amt),MEAN(dm_v_tr_sa_mx. dr_amt),SKEW(dm_v_tr_sa_mx. dr_amt),STD(dm_v_tr_sa_mx. dr_amt),SUM(dm_v_tr_sa_mx. dr_amt),COUNT(pri_cust_asset_acct_info),...,NUM_UNIQUE(pri_cust_base_info.marrige),NUM_UNIQUE(pri_cust_base_info.prof_titl),COUNT(dm_v_tr_gzdf_mx),MAX(dm_v_tr_gzdf_mx. tran_amt),MEAN(dm_v_tr_gzdf_mx. tran_amt),MIN(dm_v_tr_gzdf_mx. tran_amt),SUM(dm_v_tr_gzdf_mx. tran_amt),COUNT(dm_v_tr_sbyb_mx),MODE(dm_v_tr_sbyb_mx. tran_sts),NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)
0,0,130581199112042682,1,0.0,NaN,NaN,NaN,NaN,0.00,0.0,...,1,1,0.0,NaN,NaN,NaN,0.00,0.0,NaN,NaN
1,1,130635198511165690,3,322.0,100000.0,764.585093,16.866106,5666.331648,246196.40,0.0,...,1,1,14.0,13000.0,4022.707857,108.0,56317.91,0.0,NaN,NaN
2,2,130684198606215045,1,61.0,50000.0,3336.375410,3.939888,10650.924472,203518.90,0.0,...,1,1,0.0,NaN,NaN,NaN,0.00,0.0,NaN,NaN
3,3,130802201408149594,1,0.0,NaN,NaN,NaN,NaN,0.00,0.0,...,1,1,0.0,NaN,NaN,NaN,0.00,0.0,NaN,NaN
4,4,140902198607183528,1,4.0,0.0,0.000000,0.000000,0.000000,0.00,1.0,...,1,1,0.0,NaN,NaN,NaN,0.00,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290653,290653,654324198006010321,1,12.0,18000.0,3772.039167,1.607053,6181.982161,45264.47,0.0,...,1,1,1.0,4410.0,4410.000000,4410.0,4410.00,0.0,NaN,NaN
290654,290654,654326198608203393,2,336.0,300000.0,1966.526815,12.891771,22734.398727,660753.01,0.0,...,1,1,2.0,7500.0,6250.000000,5000.0,12500.00,0.0,NaN,NaN
290655,290655,810000200811269255,1,9.0,0.0,0.000000,0.000000,0.000000,0.00,0.0,...,1,1,3.0,117.0,52.333333,20.0,157.00,0.0,NaN,NaN
290656,290656,830000197007029225,1,7.0,690.0,154.285714,1.623706,277.360003,1080.00,1.0,...,1,1,0.0,NaN,NaN,NaN,0.00,1.0,S,1.0
290657,290657,830000200706189396,-1,6.0,0.0,0.000000,0.000000,0.000000,0.00,0.0,...,1,1,1.0,260.0,260.000000,260.0,260.00,0.0,NaN,NaN

In [3]:
for column in df.columns.to_list():
    if df[column].dtype == 'object':
        df[column].fillna(df[column].mode()[0], inplace=True)
    else:
        df[column].fillna(df[column].median(), inplace=True)
df

,Unnamed: 0,uid,star_level,COUNT(dm_v_tr_sa_mx),MAX(dm_v_tr_sa_mx. dr_amt),MEAN(dm_v_tr_sa_mx. dr_amt),SKEW(dm_v_tr_sa_mx. dr_amt),STD(dm_v_tr_sa_mx. dr_amt),SUM(dm_v_tr_sa_mx. dr_amt),COUNT(pri_cust_asset_acct_info),...,NUM_UNIQUE(pri_cust_base_info.marrige),NUM_UNIQUE(pri_cust_base_info.prof_titl),COUNT(dm_v_tr_gzdf_mx),MAX(dm_v_tr_gzdf_mx. tran_amt),MEAN(dm_v_tr_gzdf_mx. tran_amt),MIN(dm_v_tr_gzdf_mx. tran_amt),SUM(dm_v_tr_gzdf_mx. tran_amt),COUNT(dm_v_tr_sbyb_mx),MODE(dm_v_tr_sbyb_mx. tran_sts),NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)
0,0,130581199112042682,1,0.0,5000.0,389.622339,3.000000,1052.926873,0.00,0.0,...,1,1,0.0,2194.0,1330.807500,200.0,0.00,0.0,1,1.0
1,1,130635198511165690,3,322.0,100000.0,764.585093,16.866106,5666.331648,246196.40,0.0,...,1,1,14.0,13000.0,4022.707857,108.0,56317.91,0.0,1,1.0
2,2,130684198606215045,1,61.0,50000.0,3336.375410,3.939888,10650.924472,203518.90,0.0,...,1,1,0.0,2194.0,1330.807500,200.0,0.00,0.0,1,1.0
3,3,130802201408149594,1,0.0,5000.0,389.622339,3.000000,1052.926873,0.00,0.0,...,1,1,0.0,2194.0,1330.807500,200.0,0.00,0.0,1,1.0
4,4,140902198607183528,1,4.0,0.0,0.000000,0.000000,0.000000,0.00,1.0,...,1,1,0.0,2194.0,1330.807500,200.0,0.00,0.0,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290653,290653,654324198006010321,1,12.0,18000.0,3772.039167,1.607053,6181.982161,45264.47,0.0,...,1,1,1.0,4410.0,4410.000000,4410.0,4410.00,0.0,1,1.0
290654,290654,654326198608203393,2,336.0,300000.0,1966.526815,12.891771,22734.398727,660753.01,0.0,...,1,1,2.0,7500.0,6250.000000,5000.0,12500.00,0.0,1,1.0
290655,290655,810000200811269255,1,9.0,0.0,0.000000,0.000000,0.000000,0.00,0.0,...,1,1,3.0,117.0,52.333333,20.0,157.00,0.0,1,1.0
290656,290656,830000197007029225,1,7.0,690.0,154.285714,1.623706,277.360003,1080.00,1.0,...,1,1,0.0,2194.0,1330.807500,200.0,0.00,1.0,S,1.0
290657,290657,830000200706189396,-1,6.0,0.0,0.000000,0.000000,0.000000,0.00,0.0,...,1,1,1.0,260.0,260.000000,260.0,260.00,0.0,1,1.0

In [4]:
df.to_csv("./star_fillna.csv")

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./star_fillna.csv")
for column in df.columns.to_list():
    if column == 'star_level':
        print("true")

true

In [3]:
for column in df.columns.to_list():
#     print(column)
    if df[column].dtype != 'object' and column != 'star_level':
        print(column)
        if(column == 'star_level'):
            print("error")
        if(column == 'uid'):
            print("error")
        low = df[column].quantile(0.05)
        high = df[column].quantile(0.95)
        # 使用clip方法替换小于5%和大于95%的值
        df[column] = df[column].clip(lower=low, upper=high)

Unnamed: 0.1
Unnamed: 0
COUNT(dm_v_tr_sa_mx)
MAX(dm_v_tr_sa_mx. dr_amt)
MEAN(dm_v_tr_sa_mx. dr_amt)
SKEW(dm_v_tr_sa_mx. dr_amt)
STD(dm_v_tr_sa_mx. dr_amt)
SUM(dm_v_tr_sa_mx. dr_amt)
COUNT(pri_cust_asset_acct_info)
MAX(pri_cust_asset_acct_info.avg_mth)
MAX(pri_cust_asset_acct_info.avg_year)
MAX(pri_cust_asset_acct_info.bal)
MEAN(pri_cust_asset_acct_info.avg_mth)
MEAN(pri_cust_asset_acct_info.avg_year)
MEAN(pri_cust_asset_acct_info.bal)
MIN(pri_cust_asset_acct_info.avg_mth)
MIN(pri_cust_asset_acct_info.avg_year)
MIN(pri_cust_asset_acct_info.bal)
NUM_UNIQUE(pri_cust_asset_acct_info. acct_char)
NUM_UNIQUE(pri_cust_asset_acct_info.acct_sts)
NUM_UNIQUE(pri_cust_asset_acct_info.curr_type)
NUM_UNIQUE(pri_cust_asset_acct_info.frz_sts)
NUM_UNIQUE(pri_cust_asset_acct_info.is_secu_card)
NUM_UNIQUE(pri_cust_asset_acct_info.prod_code)
NUM_UNIQUE(pri_cust_asset_acct_info.stp_sts)
SUM(pri_cust_asset_acct_info.avg_mth)
SUM(pri_cust_asset_acct_info.avg_year)
SUM(pri_cust_asset_acct_info.bal)
COUNT(pri_cust_asset_info)
MAX(pri_cust_asset_info.is_extend)
MAX(pri_cust_asset_info.is_mortgage)
MAX(pri_cust_asset_info.overdue_flag)
MAX(pri_cust_asset_info.repay_type)
MAX(pri_cust_asset_info.vouch_type)
MEAN(pri_cust_asset_info.is_extend)
MEAN(pri_cust_asset_info.is_mortgage)
MEAN(pri_cust_asset_info.overdue_flag)
MEAN(pri_cust_asset_info.repay_type)
MEAN(pri_cust_asset_info.vouch_type)
MIN(pri_cust_asset_info.is_extend)
MIN(pri_cust_asset_info.is_mortgage)
MIN(pri_cust_asset_info.overdue_flag)
MIN(pri_cust_asset_info.repay_type)
MIN(pri_cust_asset_info.vouch_type)
SUM(pri_cust_asset_info.is_extend)
SUM(pri_cust_asset_info.is_mortgage)
SUM(pri_cust_asset_info.overdue_flag)
SUM(pri_cust_asset_info.repay_type)
SUM(pri_cust_asset_info.vouch_type)
COUNT(pri_cust_base_info)
NUM_UNIQUE(pri_cust_base_info.education)
NUM_UNIQUE(pri_cust_base_info.is_black)
NUM_UNIQUE(pri_cust_base_info.is_contact)
NUM_UNIQUE(pri_cust_base_info.is_employee)
NUM_UNIQUE(pri_cust_base_info.is_mgr_dep)
NUM_UNIQUE(pri_cust_base_info.is_shareholder)
NUM_UNIQUE(pri_cust_base_info.marrige)
NUM_UNIQUE(pri_cust_base_info.prof_titl)
COUNT(dm_v_tr_gzdf_mx)
MAX(dm_v_tr_gzdf_mx. tran_amt)
MEAN(dm_v_tr_gzdf_mx. tran_amt)
MIN(dm_v_tr_gzdf_mx. tran_amt)
SUM(dm_v_tr_gzdf_mx. tran_amt)
COUNT(dm_v_tr_sbyb_mx)
NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)

In [4]:
df.drop(columns='Unnamed: 0.1',axis=1,inplace=True)
df.drop(columns='Unnamed: 0',axis=1,inplace=True)
df

,uid,star_level,COUNT(dm_v_tr_sa_mx),MAX(dm_v_tr_sa_mx. dr_amt),MEAN(dm_v_tr_sa_mx. dr_amt),SKEW(dm_v_tr_sa_mx. dr_amt),STD(dm_v_tr_sa_mx. dr_amt),SUM(dm_v_tr_sa_mx. dr_amt),COUNT(pri_cust_asset_acct_info),MAX(pri_cust_asset_acct_info.avg_mth),...,NUM_UNIQUE(pri_cust_base_info.marrige),NUM_UNIQUE(pri_cust_base_info.prof_titl),COUNT(dm_v_tr_gzdf_mx),MAX(dm_v_tr_gzdf_mx. tran_amt),MEAN(dm_v_tr_gzdf_mx. tran_amt),MIN(dm_v_tr_gzdf_mx. tran_amt),SUM(dm_v_tr_gzdf_mx. tran_amt),COUNT(dm_v_tr_sbyb_mx),MODE(dm_v_tr_sbyb_mx. tran_sts),NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)
0,130581199112042682,1,0.0,5000.0,389.622339,3.000000,1052.926873,0.000,0.0,9.57,...,1,1,0.0,2194.0000,1330.807500,200.000,0.0,0.0,1,1.0
1,130635198511165690,3,322.0,100000.0,764.585093,8.609999,5666.331648,246196.400,0.0,9.57,...,1,1,12.0,9842.4435,4022.707857,108.000,40000.0,0.0,1,1.0
2,130684198606215045,1,61.0,50000.0,3336.375410,3.939888,10650.924472,203518.900,0.0,9.57,...,1,1,0.0,2194.0000,1330.807500,200.000,0.0,0.0,1,1.0
3,130802201408149594,1,0.0,5000.0,389.622339,3.000000,1052.926873,0.000,0.0,9.57,...,1,1,0.0,2194.0000,1330.807500,200.000,0.0,0.0,1,1.0
4,140902198607183528,1,4.0,0.0,0.000000,0.000000,0.000000,0.000,1.0,9.80,...,1,1,0.0,2194.0000,1330.807500,200.000,0.0,0.0,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290653,654324198006010321,1,12.0,18000.0,3772.039167,1.607053,6181.982161,45264.470,0.0,9.57,...,1,1,1.0,4410.0000,4410.000000,2578.524,4410.0,0.0,1,1.0
290654,654326198608203393,2,332.0,195000.0,1966.526815,8.609999,22734.398727,594533.601,0.0,9.57,...,1,1,2.0,7500.0000,4923.063087,2578.524,12500.0,0.0,1,1.0
290655,810000200811269255,1,9.0,0.0,0.000000,0.000000,0.000000,0.000,0.0,9.57,...,1,1,3.0,117.0000,100.000000,31.656,157.0,0.0,1,1.0
290656,830000197007029225,1,7.0,690.0,154.285714,1.623706,277.360003,1080.000,1.0,60.92,...,1,1,0.0,2194.0000,1330.807500,200.000,0.0,1.0,S,1.0
290657,830000200706189396,-1,6.0,0.0,0.000000,0.000000,0.000000,0.000,0.0,9.57,...,1,1,1.0,260.0000,260.000000,260.000,260.0,0.0,1,1.0

In [5]:
df.to_csv("./star_error_data.csv")

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("./star_error_data.csv",dtype=None)
print(df.dtypes)

Unnamed: 0                                 int64
uid                                       object
star_level                                 int64
COUNT(dm_v_tr_sa_mx)                     float64
MAX(dm_v_tr_sa_mx. dr_amt)               float64
                                          ...
MIN(dm_v_tr_gzdf_mx. tran_amt)           float64
SUM(dm_v_tr_gzdf_mx. tran_amt)           float64
COUNT(dm_v_tr_sbyb_mx)                   float64
MODE(dm_v_tr_sbyb_mx. tran_sts)           object
NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)    float64
Length: 82, dtype: object

In [ ]:
df['MODE(dm_v_tr_huanb_mx.tran_type)'] = pd.to_numeric(df['MODE(dm_v_tr_huanb_mx.tran_type)'],errors="coerce")
df['MODE(dm_v_tr_huanb_mx.tran_type)'] = df['MODE(dm_v_tr_huanb_mx.tran_type)'].astype(float)
print(df['MODE(dm_v_tr_huanb_mx.tran_type)'].unique())
df['MODE(dm_v_tr_huanb_mx.tran_type)'] = df['MODE(dm_v_tr_huanb_mx.tran_type)'].fillna(0.0)
print(df['MODE(dm_v_tr_huanb_mx.tran_type)'].unique())

In [3]:

for column in df.columns.to_list():
    print(column)
    print(df[column].dtype)
    if column != 'uid' and df[column].dtype == 'object':
        print(column)
        encoder= LabelEncoder().fit(df[column])
        df[column] = encoder.transform(df[column])
df.head()

Unnamed: 0
int64
uid
object
star_level
int64
COUNT(dm_v_tr_sa_mx)
float64
MAX(dm_v_tr_sa_mx. dr_amt)
float64
MEAN(dm_v_tr_sa_mx. dr_amt)
float64
SKEW(dm_v_tr_sa_mx. dr_amt)
float64
STD(dm_v_tr_sa_mx. dr_amt)
float64
SUM(dm_v_tr_sa_mx. dr_amt)
float64
COUNT(pri_cust_asset_acct_info)
float64
MAX(pri_cust_asset_acct_info.avg_mth)
float64
MAX(pri_cust_asset_acct_info.avg_year)
float64
MAX(pri_cust_asset_acct_info.bal)
float64
MEAN(pri_cust_asset_acct_info.avg_mth)
float64
MEAN(pri_cust_asset_acct_info.avg_year)
float64
MEAN(pri_cust_asset_acct_info.bal)
float64
MIN(pri_cust_asset_acct_info.avg_mth)
float64
MIN(pri_cust_asset_acct_info.avg_year)
float64
MIN(pri_cust_asset_acct_info.bal)
float64
MODE(pri_cust_asset_acct_info. acct_char)
object
MODE(pri_cust_asset_acct_info. acct_char)
MODE(pri_cust_asset_acct_info.acct_sts)
object
MODE(pri_cust_asset_acct_info.acct_sts)
MODE(pri_cust_asset_acct_info.curr_type)
object
MODE(pri_cust_asset_acct_info.curr_type)
MODE(pri_cust_asset_acct_info.frz_sts)
object
MODE(pri_cust_asset_acct_info.frz_sts)
MODE(pri_cust_asset_acct_info.is_secu_card)
object
MODE(pri_cust_asset_acct_info.is_secu_card)
MODE(pri_cust_asset_acct_info.prod_code)
object
MODE(pri_cust_asset_acct_info.prod_code)
MODE(pri_cust_asset_acct_info.stp_sts)
object
MODE(pri_cust_asset_acct_info.stp_sts)
NUM_UNIQUE(pri_cust_asset_acct_info. acct_char)
float64
NUM_UNIQUE(pri_cust_asset_acct_info.acct_sts)
float64
NUM_UNIQUE(pri_cust_asset_acct_info.curr_type)
float64
NUM_UNIQUE(pri_cust_asset_acct_info.frz_sts)
float64
NUM_UNIQUE(pri_cust_asset_acct_info.is_secu_card)
float64
NUM_UNIQUE(pri_cust_asset_acct_info.prod_code)
float64
NUM_UNIQUE(pri_cust_asset_acct_info.stp_sts)
float64
SUM(pri_cust_asset_acct_info.avg_mth)
float64
SUM(pri_cust_asset_acct_info.avg_year)
float64
SUM(pri_cust_asset_acct_info.bal)
float64
COUNT(pri_cust_asset_info)
float64
MAX(pri_cust_asset_info.is_extend)
float64
MAX(pri_cust_asset_info.is_mortgage)
float64
MAX(pri_cust_asset_info.overdue_flag)
float64
MAX(pri_cust_asset_info.repay_type)
float64
MAX(pri_cust_asset_info.vouch_type)
float64
MEAN(pri_cust_asset_info.is_extend)
float64
MEAN(pri_cust_asset_info.is_mortgage)
float64
MEAN(pri_cust_asset_info.overdue_flag)
float64
MEAN(pri_cust_asset_info.repay_type)
float64
MEAN(pri_cust_asset_info.vouch_type)
float64
MIN(pri_cust_asset_info.is_extend)
float64
MIN(pri_cust_asset_info.is_mortgage)
float64
MIN(pri_cust_asset_info.overdue_flag)
float64
MIN(pri_cust_asset_info.repay_type)
float64
MIN(pri_cust_asset_info.vouch_type)
float64
SUM(pri_cust_asset_info.is_extend)
float64
SUM(pri_cust_asset_info.is_mortgage)
float64
SUM(pri_cust_asset_info.overdue_flag)
float64
SUM(pri_cust_asset_info.repay_type)
float64
SUM(pri_cust_asset_info.vouch_type)
float64
COUNT(pri_cust_base_info)
int64
MODE(pri_cust_base_info.education)
object
MODE(pri_cust_base_info.education)
MODE(pri_cust_base_info.is_black)
object
MODE(pri_cust_base_info.is_black)
MODE(pri_cust_base_info.is_contact)
object
MODE(pri_cust_base_info.is_contact)
MODE(pri_cust_base_info.is_employee)
object
MODE(pri_cust_base_info.is_employee)
MODE(pri_cust_base_info.is_mgr_dep)
object
MODE(pri_cust_base_info.is_mgr_dep)
MODE(pri_cust_base_info.is_shareholder)
object
MODE(pri_cust_base_info.is_shareholder)
MODE(pri_cust_base_info.marrige)
object
MODE(pri_cust_base_info.marrige)
MODE(pri_cust_base_info.prof_titl)
object
MODE(pri_cust_base_info.prof_titl)
NUM_UNIQUE(pri_cust_base_info.education)
int64
NUM_UNIQUE(pri_cust_base_info.is_black)
int64
NUM_UNIQUE(pri_cust_base_info.is_contact)
int64
NUM_UNIQUE(pri_cust_base_info.is_employee)
int64
NUM_UNIQUE(pri_cust_base_info.is_mgr_dep)
int64
NUM_UNIQUE(pri_cust_base_info.is_shareholder)
int64
NUM_UNIQUE(pri_cust_base_info.marrige)
int64
NUM_UNIQUE(pri_cust_base_info.prof_titl)
int64
COUNT(dm_v_tr_gzdf_mx)
float64
MAX(dm_v_tr_gzdf_mx. tran_amt)
float64
MEAN(dm_v_tr_gzdf_mx. tran_amt)
float64
MIN(dm_v_tr_gzdf_mx. tran_amt)
float64
SUM(dm_v_tr_gzdf_mx. tran_amt)
float64
COUNT(dm_v_tr_sbyb_mx)
float64
MODE(dm_v_tr_sbyb_mx. tran_sts)
object
MODE(dm_v_tr_sbyb_mx. tran_sts)
NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)
float64

,Unnamed: 0,uid,star_level,COUNT(dm_v_tr_sa_mx),MAX(dm_v_tr_sa_mx. dr_amt),MEAN(dm_v_tr_sa_mx. dr_amt),SKEW(dm_v_tr_sa_mx. dr_amt),STD(dm_v_tr_sa_mx. dr_amt),SUM(dm_v_tr_sa_mx. dr_amt),COUNT(pri_cust_asset_acct_info),...,NUM_UNIQUE(pri_cust_base_info.marrige),NUM_UNIQUE(pri_cust_base_info.prof_titl),COUNT(dm_v_tr_gzdf_mx),MAX(dm_v_tr_gzdf_mx. tran_amt),MEAN(dm_v_tr_gzdf_mx. tran_amt),MIN(dm_v_tr_gzdf_mx. tran_amt),SUM(dm_v_tr_gzdf_mx. tran_amt),COUNT(dm_v_tr_sbyb_mx),MODE(dm_v_tr_sbyb_mx. tran_sts),NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)
0,0,130581199112042682,1,0.0,5000.0,389.622339,3.000000,1052.926873,0.0,0.0,...,1,1,0.0,2194.0000,1330.807500,200.0,0.0,0.0,0,1.0
1,1,130635198511165690,3,322.0,100000.0,764.585093,8.609999,5666.331648,246196.4,0.0,...,1,1,12.0,9842.4435,4022.707857,108.0,40000.0,0.0,0,1.0
2,2,130684198606215045,1,61.0,50000.0,3336.375410,3.939888,10650.924472,203518.9,0.0,...,1,1,0.0,2194.0000,1330.807500,200.0,0.0,0.0,0,1.0
3,3,130802201408149594,1,0.0,5000.0,389.622339,3.000000,1052.926873,0.0,0.0,...,1,1,0.0,2194.0000,1330.807500,200.0,0.0,0.0,0,1.0
4,4,140902198607183528,1,4.0,0.0,0.000000,0.000000,0.000000,0.0,1.0,...,1,1,0.0,2194.0000,1330.807500,200.0,0.0,0.0,0,1.0

In [4]:
df.to_csv("./star_encoded.csv")

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
scaler = StandardScaler()
df = pd.read_csv("./star_encoded.csv",dtype=None)
df_columns = df.columns.to_list()
df_columns.remove('uid')
df_columns.remove('star_level')
print(df_columns)
df[df_columns] = scaler.fit_transform(df[df_columns])
df.head()

['Unnamed: 0.1', 'Unnamed: 0', 'COUNT(dm_v_tr_sa_mx)', 'MAX(dm_v_tr_sa_mx. dr_amt)', 'MEAN(dm_v_tr_sa_mx. dr_amt)', 'SKEW(dm_v_tr_sa_mx. dr_amt)', 'STD(dm_v_tr_sa_mx. dr_amt)', 'SUM(dm_v_tr_sa_mx. dr_amt)', 'COUNT(pri_cust_asset_acct_info)', 'MAX(pri_cust_asset_acct_info.avg_mth)', 'MAX(pri_cust_asset_acct_info.avg_year)', 'MAX(pri_cust_asset_acct_info.bal)', 'MEAN(pri_cust_asset_acct_info.avg_mth)', 'MEAN(pri_cust_asset_acct_info.avg_year)', 'MEAN(pri_cust_asset_acct_info.bal)', 'MIN(pri_cust_asset_acct_info.avg_mth)', 'MIN(pri_cust_asset_acct_info.avg_year)', 'MIN(pri_cust_asset_acct_info.bal)', 'MODE(pri_cust_asset_acct_info. acct_char)', 'MODE(pri_cust_asset_acct_info.acct_sts)', 'MODE(pri_cust_asset_acct_info.curr_type)', 'MODE(pri_cust_asset_acct_info.frz_sts)', 'MODE(pri_cust_asset_acct_info.is_secu_card)', 'MODE(pri_cust_asset_acct_info.prod_code)', 'MODE(pri_cust_asset_acct_info.stp_sts)', 'NUM_UNIQUE(pri_cust_asset_acct_info. acct_char)', 'NUM_UNIQUE(pri_cust_asset_acct_info.acct_sts)', 'NUM_UNIQUE(pri_cust_asset_acct_info.curr_type)', 'NUM_UNIQUE(pri_cust_asset_acct_info.frz_sts)', 'NUM_UNIQUE(pri_cust_asset_acct_info.is_secu_card)', 'NUM_UNIQUE(pri_cust_asset_acct_info.prod_code)', 'NUM_UNIQUE(pri_cust_asset_acct_info.stp_sts)', 'SUM(pri_cust_asset_acct_info.avg_mth)', 'SUM(pri_cust_asset_acct_info.avg_year)', 'SUM(pri_cust_asset_acct_info.bal)', 'COUNT(pri_cust_asset_info)', 'MAX(pri_cust_asset_info.is_extend)', 'MAX(pri_cust_asset_info.is_mortgage)', 'MAX(pri_cust_asset_info.overdue_flag)', 'MAX(pri_cust_asset_info.repay_type)', 'MAX(pri_cust_asset_info.vouch_type)', 'MEAN(pri_cust_asset_info.is_extend)', 'MEAN(pri_cust_asset_info.is_mortgage)', 'MEAN(pri_cust_asset_info.overdue_flag)', 'MEAN(pri_cust_asset_info.repay_type)', 'MEAN(pri_cust_asset_info.vouch_type)', 'MIN(pri_cust_asset_info.is_extend)', 'MIN(pri_cust_asset_info.is_mortgage)', 'MIN(pri_cust_asset_info.overdue_flag)', 'MIN(pri_cust_asset_info.repay_type)', 'MIN(pri_cust_asset_info.vouch_type)', 'SUM(pri_cust_asset_info.is_extend)', 'SUM(pri_cust_asset_info.is_mortgage)', 'SUM(pri_cust_asset_info.overdue_flag)', 'SUM(pri_cust_asset_info.repay_type)', 'SUM(pri_cust_asset_info.vouch_type)', 'COUNT(pri_cust_base_info)', 'MODE(pri_cust_base_info.education)', 'MODE(pri_cust_base_info.is_black)', 'MODE(pri_cust_base_info.is_contact)', 'MODE(pri_cust_base_info.is_employee)', 'MODE(pri_cust_base_info.is_mgr_dep)', 'MODE(pri_cust_base_info.is_shareholder)', 'MODE(pri_cust_base_info.marrige)', 'MODE(pri_cust_base_info.prof_titl)', 'NUM_UNIQUE(pri_cust_base_info.education)', 'NUM_UNIQUE(pri_cust_base_info.is_black)', 'NUM_UNIQUE(pri_cust_base_info.is_contact)', 'NUM_UNIQUE(pri_cust_base_info.is_employee)', 'NUM_UNIQUE(pri_cust_base_info.is_mgr_dep)', 'NUM_UNIQUE(pri_cust_base_info.is_shareholder)', 'NUM_UNIQUE(pri_cust_base_info.marrige)', 'NUM_UNIQUE(pri_cust_base_info.prof_titl)', 'COUNT(dm_v_tr_gzdf_mx)', 'MAX(dm_v_tr_gzdf_mx. tran_amt)', 'MEAN(dm_v_tr_gzdf_mx. tran_amt)', 'MIN(dm_v_tr_gzdf_mx. tran_amt)', 'SUM(dm_v_tr_gzdf_mx. tran_amt)', 'COUNT(dm_v_tr_sbyb_mx)', 'MODE(dm_v_tr_sbyb_mx. tran_sts)', 'NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)']

,Unnamed: 0.1,Unnamed: 0,uid,star_level,COUNT(dm_v_tr_sa_mx),MAX(dm_v_tr_sa_mx. dr_amt),MEAN(dm_v_tr_sa_mx. dr_amt),SKEW(dm_v_tr_sa_mx. dr_amt),STD(dm_v_tr_sa_mx. dr_amt),SUM(dm_v_tr_sa_mx. dr_amt),...,NUM_UNIQUE(pri_cust_base_info.marrige),NUM_UNIQUE(pri_cust_base_info.prof_titl),COUNT(dm_v_tr_gzdf_mx),MAX(dm_v_tr_gzdf_mx. tran_amt),MEAN(dm_v_tr_gzdf_mx. tran_amt),MIN(dm_v_tr_gzdf_mx. tran_amt),SUM(dm_v_tr_gzdf_mx. tran_amt),COUNT(dm_v_tr_sbyb_mx),MODE(dm_v_tr_sbyb_mx. tran_sts),NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)
0,-1.732045,-1.732045,130581199112042682,1,-0.650138,-0.395297,-0.410145,-0.132824,-0.405856,-0.506595,...,0.0,0.0,-0.499799,-0.204404,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
1,-1.732033,-1.732033,130635198511165690,3,3.190510,1.586118,-0.203771,2.439056,0.303662,1.113832,...,0.0,0.0,3.228379,3.338046,2.295653,-0.452617,3.531513,-0.635444,-0.308942,0.0
2,-1.732021,-1.732021,130684198606215045,1,0.077438,0.543268,1.211703,0.298063,1.070267,0.832935,...,0.0,0.0,-0.499799,-0.204404,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
3,-1.732009,-1.732009,130802201408149594,1,-0.650138,-0.395297,-0.410145,-0.132824,-0.405856,-0.506595,...,0.0,0.0,-0.499799,-0.204404,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
4,-1.731997,-1.731997,140902198607183528,1,-0.602428,-0.499582,-0.624587,-1.508162,-0.567791,-0.506595,...,0.0,0.0,-0.499799,-0.204404,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0

In [3]:
df.drop('Unnamed: 0.1',axis=1, inplace=True)
df.drop('Unnamed: 0',axis=1, inplace=True)
df.to_csv("./star_final.csv")