In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./star_final.csv")

In [3]:
corr_matrix = df.corr()
corr_matrix

C:\Users\10728\AppData\Local\Temp\ipykernel_32284\2355143037.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr_matrix = df.corr()

,Unnamed: 0,star_level,COUNT(dm_v_tr_sa_mx),MAX(dm_v_tr_sa_mx. dr_amt),MEAN(dm_v_tr_sa_mx. dr_amt),SKEW(dm_v_tr_sa_mx. dr_amt),STD(dm_v_tr_sa_mx. dr_amt),SUM(dm_v_tr_sa_mx. dr_amt),COUNT(pri_cust_asset_acct_info),MAX(pri_cust_asset_acct_info.avg_mth),...,NUM_UNIQUE(pri_cust_base_info.marrige),NUM_UNIQUE(pri_cust_base_info.prof_titl),COUNT(dm_v_tr_gzdf_mx),MAX(dm_v_tr_gzdf_mx. tran_amt),MEAN(dm_v_tr_gzdf_mx. tran_amt),MIN(dm_v_tr_gzdf_mx. tran_amt),SUM(dm_v_tr_gzdf_mx. tran_amt),COUNT(dm_v_tr_sbyb_mx),MODE(dm_v_tr_sbyb_mx. tran_sts),NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)
Unnamed: 0,1.000000,-0.114940,0.028567,0.003205,0.003556,-0.073797,-0.005365,0.025596,-0.149100,-0.054119,...,NaN,NaN,-0.059835,-0.032328,0.008505,-0.013979,-0.010724,-0.124012,-0.054008,NaN
star_level,-0.114940,1.000000,0.129041,0.220045,0.186052,0.202607,0.213069,0.193907,0.090877,0.161171,...,NaN,NaN,0.166325,0.130321,0.100938,0.081272,0.148282,0.146269,0.013957,NaN
COUNT(dm_v_tr_sa_mx),0.028567,0.129041,1.000000,0.360850,0.162571,0.639456,0.223850,0.581054,0.122413,0.173223,...,NaN,NaN,0.303237,0.239692,0.222548,0.147035,0.317828,0.103697,-0.023716,NaN
MAX(dm_v_tr_sa_mx. dr_amt),0.003205,0.220045,0.360850,1.000000,0.832947,0.461305,0.938850,0.858344,0.095270,0.157543,...,NaN,NaN,0.159740,0.218767,0.190234,0.106106,0.216463,0.082058,-0.039154,NaN
MEAN(dm_v_tr_sa_mx. dr_amt),0.003556,0.186052,0.162571,0.832947,1.000000,0.214676,0.945678,0.755505,0.054854,0.127994,...,NaN,NaN,0.108833,0.209596,0.190951,0.115612,0.184178,0.039786,-0.050000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MIN(dm_v_tr_gzdf_mx. tran_amt),-0.013979,0.081272,0.147035,0.106106,0.115612,0.132192,0.106898,0.118801,0.061442,0.088490,...,NaN,NaN,0.257479,0.459159,0.692872,1.000000,0.462275,0.082436,-0.018174,NaN
SUM(dm_v_tr_gzdf_mx. tran_amt),-0.010724,0.148282,0.317828,0.216463,0.184178,0.263899,0.193060,0.264517,0.093307,0.150609,...,NaN,NaN,0.825396,0.802813,0.754082,0.462275,1.000000,0.011252,-0.043110,NaN
COUNT(dm_v_tr_sbyb_mx),-0.124012,0.146269,0.103697,0.082058,0.039786,0.146306,0.066118,0.068185,0.169445,0.109003,...,NaN,NaN,0.032297,0.015701,0.036542,0.082436,0.011252,1.000000,0.222554,NaN
MODE(dm_v_tr_sbyb_mx. tran_sts),-0.054008,0.013957,-0.023716,-0.039154,-0.050000,0.019769,-0.041160,-0.052657,0.038660,-0.008453,...,NaN,NaN,-0.009672,-0.049821,-0.049334,-0.018174,-0.043110,0.222554,1.000000,NaN
NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
corr_matrix.to_csv("./corr_matrix_star.csv")

In [5]:
corr_series = corr_matrix.mask(np.triu(np.ones(corr_matrix.shape)).astype(np.bool)).stack()
corr_series

C:\Users\10728\AppData\Local\Temp\ipykernel_32284\481195337.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  corr_series = corr_matrix.mask(np.triu(np.ones(corr_matrix.shape)).astype(np.bool)).stack()

star_level                       Unnamed: 0                        -0.114940
COUNT(dm_v_tr_sa_mx)             Unnamed: 0                         0.028567
                                 star_level                         0.129041
MAX(dm_v_tr_sa_mx. dr_amt)       Unnamed: 0                         0.003205
                                 star_level                         0.220045
                                                                      ...
MODE(dm_v_tr_sbyb_mx. tran_sts)  MAX(dm_v_tr_gzdf_mx. tran_amt)    -0.049821
                                 MEAN(dm_v_tr_gzdf_mx. tran_amt)   -0.049334
                                 MIN(dm_v_tr_gzdf_mx. tran_amt)    -0.018174
                                 SUM(dm_v_tr_gzdf_mx. tran_amt)    -0.043110
                                 COUNT(dm_v_tr_sbyb_mx)             0.222554
Length: 1953, dtype: float64

In [6]:
to_drop = corr_series[abs(corr_series) >= 0.7].index.tolist()

In [7]:
to_drop
drop = []
index = 0
for t in to_drop:
    if (t[0][0:4] == 'MEAN' and t[1][0:4] == 'MAX(') or (t[1][0:4] == 'MEAN' and t[0][0:4] == 'MAX('):
        if t[1][0:4] == 'MAX(':
            to_drop.pop(index)
            drop.append(t[1])
        else:
            to_drop.pop(index)
            drop.append(t[0])
    if (t[0][0:4] == 'MEAN' and t[1][0:4] == 'MIN(') or (t[1][0:4] == 'MEAN' and t[0][0:4] == 'MIN('):
        if t[1][0:4] == 'MIN(':
            drop.append(t[1])
            to_drop.pop(index)
        else:
            drop.append(t[0])
            to_drop.pop(index)
    index = index + 1

In [28]:
drop

['MAX(dm_v_tr_contract_mx.buss_amt)',
 'MIN(dm_v_tr_contract_mx.buss_amt)',
 'MAX(dm_v_tr_duebill_mx.buss_amt)',
 'MAX(dm_v_tr_duebill_mx.buss_type)',
 'MAX(dm_v_tr_duebill_mx.pay_freq)',
 'MAX(dm_v_tr_duebill_mx.bal)',
 'MAX(dm_v_tr_contract_mx.buss_amt)',
 'MAX(dm_v_tr_duebill_mx.buss_amt)',
 'MAX(dm_v_tr_duebill_mx.buss_type)',
 'MAX(dm_v_tr_duebill_mx.bal)',
 'MAX(dm_v_tr_contract_mx.term_mth)',
 'MAX(dm_v_tr_duebill_mx.buss_type)',
 'MIN(dm_v_tr_duebill_mx.buss_amt)',
 'MIN(dm_v_tr_duebill_mx.buss_type)',
 'MIN(dm_v_tr_duebill_mx.buss_type)',
 'MIN(dm_v_tr_duebill_mx.pay_freq)',
 'MIN(dm_v_tr_duebill_mx.pay_freq)',
 'MAX(dm_v_tr_huanb_mx.pay_term)',
 'MAX(dm_v_tr_contract_mx.term_mth)',
 'MAX(dm_v_tr_huanb_mx.pay_term)',
 'MAX(dm_v_tr_huanb_mx.tran_amt)',
 'MAX(dm_v_tr_huanx_mx. cac_intc_pr)',
 'MAX(dm_v_tr_huanx_mx.tran_amt)',
 'MAX(dm_v_tr_sa_mx. dr_amt)',
 'MAX(pri_cust_asset_acct_info.avg_mth)',
 'MAX(pri_cust_asset_acct_info.bal)',
 'MAX(pri_cust_asset_acct_info.avg_year)',
 'MAX(pri_cust_asset_acct_info.avg_mth)',
 'MAX(pri_cust_asset_acct_info.bal)',
 'MAX(pri_cust_asset_info.is_extend)',
 'MAX(pri_cust_asset_info.vouch_type)',
 'MAX(pri_cust_asset_info.is_mortgage)',
 'MAX(pri_cust_asset_info.overdue_flag)',
 'MAX(pri_cust_asset_info.overdue_flag)',
 'MAX(pri_cust_asset_info.is_extend)',
 'MAX(pri_cust_asset_info.vouch_type)',
 'MIN(pri_cust_asset_info.is_extend)',
 'MIN(pri_cust_asset_info.is_extend)',
 'MIN(pri_cust_asset_info.is_mortgage)',
 'MIN(pri_cust_asset_info.is_mortgage)',
 'MIN(pri_cust_asset_info.overdue_flag)',
 'MIN(pri_cust_asset_info.repay_type)',
 'MIN(pri_cust_asset_info.vouch_type)',
 'MIN(pri_cust_asset_info.vouch_type)',
 'MAX(pri_cust_liab_acct_info.acct_sts)',
 'MAX(dm_v_tr_gzdf_mx. tran_amt)',
 'MAX(pri_cust_liab_info.all_bal)',
 'MAX(dm_v_tr_duebill_mx.buss_amt)',
 'MAX(pri_cust_liab_info.all_bal)',
 'MIN(pri_cust_liab_info.all_bal)',
 'MIN(pri_cust_liab_info.all_bal)']

In [8]:
print(len(drop))

26

In [9]:
df.drop(columns=drop,axis=1,inplace=True)
df.to_csv("./star_after_corr.csv")

In [10]:
df

,Unnamed: 0,uid,star_level,COUNT(dm_v_tr_sa_mx),MEAN(dm_v_tr_sa_mx. dr_amt),SKEW(dm_v_tr_sa_mx. dr_amt),STD(dm_v_tr_sa_mx. dr_amt),SUM(dm_v_tr_sa_mx. dr_amt),COUNT(pri_cust_asset_acct_info),MEAN(pri_cust_asset_acct_info.avg_mth),...,NUM_UNIQUE(pri_cust_base_info.is_shareholder),NUM_UNIQUE(pri_cust_base_info.marrige),NUM_UNIQUE(pri_cust_base_info.prof_titl),COUNT(dm_v_tr_gzdf_mx),MEAN(dm_v_tr_gzdf_mx. tran_amt),MIN(dm_v_tr_gzdf_mx. tran_amt),SUM(dm_v_tr_gzdf_mx. tran_amt),COUNT(dm_v_tr_sbyb_mx),MODE(dm_v_tr_sbyb_mx. tran_sts),NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)
0,0,130581199112042682,1,-0.650138,-0.410145,-0.132824,-0.405856,-0.506595,-0.903042,-0.362930,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
1,1,130635198511165690,3,3.190510,-0.203771,2.439056,0.303662,1.113832,-0.903042,-0.362930,...,0.0,0.0,0.0,3.228379,2.295653,-0.452617,3.531513,-0.635444,-0.308942,0.0
2,2,130684198606215045,1,0.077438,1.211703,0.298063,1.070267,0.832935,-0.903042,-0.362930,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
3,3,130802201408149594,1,-0.650138,-0.410145,-0.132824,-0.405856,-0.506595,-0.903042,-0.362930,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
4,4,140902198607183528,1,-0.602428,-0.624587,-1.508162,-0.567791,-0.506595,0.242028,-0.344120,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290653,290653,654324198006010321,1,-0.507008,1.451485,-0.771415,0.382966,-0.208672,-0.903042,-0.362930,...,0.0,0.0,0.0,-0.189118,2.652135,3.635567,0.040531,-0.635444,-0.308942,0.0
290654,290654,654326198608203393,2,3.309785,0.457759,2.439056,2.928644,3.406533,-0.903042,-0.362930,...,0.0,0.0,0.0,0.121564,3.124384,3.635567,0.834069,-0.635444,-0.308942,0.0
290655,290655,810000200811269255,1,-0.542790,-0.624587,-1.508162,-0.567791,-0.506595,-0.903042,-0.362930,...,0.0,0.0,0.0,0.432245,-1.315002,-0.578950,-0.376641,-0.635444,-0.308942,0.0
290656,290656,830000197007029225,1,-0.566645,-0.539670,-0.763781,-0.525134,-0.499487,0.242028,0.030035,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,0.419081,3.237170,0.0
290657,290657,830000200706189396,-1,-0.578573,-0.624587,-1.508162,-0.567791,-0.506595,-0.903042,-0.362930,...,0.0,0.0,0.0,-0.189118,-1.167730,-0.201090,-0.366538,-0.635444,-0.308942,0.0

In [11]:
import pandas as pd
import statsmodels.api as sm

In [12]:
df = pd.read_csv("./star_after_corr.csv")

In [13]:
df

,Unnamed: 0.1,Unnamed: 0,uid,star_level,COUNT(dm_v_tr_sa_mx),MEAN(dm_v_tr_sa_mx. dr_amt),SKEW(dm_v_tr_sa_mx. dr_amt),STD(dm_v_tr_sa_mx. dr_amt),SUM(dm_v_tr_sa_mx. dr_amt),COUNT(pri_cust_asset_acct_info),...,NUM_UNIQUE(pri_cust_base_info.is_shareholder),NUM_UNIQUE(pri_cust_base_info.marrige),NUM_UNIQUE(pri_cust_base_info.prof_titl),COUNT(dm_v_tr_gzdf_mx),MEAN(dm_v_tr_gzdf_mx. tran_amt),MIN(dm_v_tr_gzdf_mx. tran_amt),SUM(dm_v_tr_gzdf_mx. tran_amt),COUNT(dm_v_tr_sbyb_mx),MODE(dm_v_tr_sbyb_mx. tran_sts),NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)
0,0,0,130581199112042682,1,-0.650138,-0.410145,-0.132824,-0.405856,-0.506595,-0.903042,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
1,1,1,130635198511165690,3,3.190510,-0.203771,2.439056,0.303662,1.113832,-0.903042,...,0.0,0.0,0.0,3.228379,2.295653,-0.452617,3.531513,-0.635444,-0.308942,0.0
2,2,2,130684198606215045,1,0.077438,1.211703,0.298063,1.070267,0.832935,-0.903042,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
3,3,3,130802201408149594,1,-0.650138,-0.410145,-0.132824,-0.405856,-0.506595,-0.903042,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
4,4,4,140902198607183528,1,-0.602428,-0.624587,-1.508162,-0.567791,-0.506595,0.242028,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290653,290653,290653,654324198006010321,1,-0.507008,1.451485,-0.771415,0.382966,-0.208672,-0.903042,...,0.0,0.0,0.0,-0.189118,2.652135,3.635567,0.040531,-0.635444,-0.308942,0.0
290654,290654,290654,654326198608203393,2,3.309785,0.457759,2.439056,2.928644,3.406533,-0.903042,...,0.0,0.0,0.0,0.121564,3.124384,3.635567,0.834069,-0.635444,-0.308942,0.0
290655,290655,290655,810000200811269255,1,-0.542790,-0.624587,-1.508162,-0.567791,-0.506595,-0.903042,...,0.0,0.0,0.0,0.432245,-1.315002,-0.578950,-0.376641,-0.635444,-0.308942,0.0
290656,290656,290656,830000197007029225,1,-0.566645,-0.539670,-0.763781,-0.525134,-0.499487,0.242028,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,0.419081,3.237170,0.0
290657,290657,290657,830000200706189396,-1,-0.578573,-0.624587,-1.508162,-0.567791,-0.506595,-0.903042,...,0.0,0.0,0.0,-0.189118,-1.167730,-0.201090,-0.366538,-0.635444,-0.308942,0.0

In [14]:
df.drop(columns='Unnamed: 0',axis=1,inplace=True)
x_list = df.columns.to_list()
print(x_list)

['Unnamed: 0.1', 'uid', 'star_level', 'COUNT(dm_v_tr_sa_mx)', 'MEAN(dm_v_tr_sa_mx. dr_amt)', 'SKEW(dm_v_tr_sa_mx. dr_amt)', 'STD(dm_v_tr_sa_mx. dr_amt)', 'SUM(dm_v_tr_sa_mx. dr_amt)', 'COUNT(pri_cust_asset_acct_info)', 'MEAN(pri_cust_asset_acct_info.avg_mth)', 'MEAN(pri_cust_asset_acct_info.avg_year)', 'MEAN(pri_cust_asset_acct_info.bal)', 'MODE(pri_cust_asset_acct_info. acct_char)', 'MODE(pri_cust_asset_acct_info.acct_sts)', 'MODE(pri_cust_asset_acct_info.curr_type)', 'MODE(pri_cust_asset_acct_info.frz_sts)', 'MODE(pri_cust_asset_acct_info.is_secu_card)', 'MODE(pri_cust_asset_acct_info.prod_code)', 'MODE(pri_cust_asset_acct_info.stp_sts)', 'NUM_UNIQUE(pri_cust_asset_acct_info. acct_char)', 'NUM_UNIQUE(pri_cust_asset_acct_info.acct_sts)', 'NUM_UNIQUE(pri_cust_asset_acct_info.curr_type)', 'NUM_UNIQUE(pri_cust_asset_acct_info.frz_sts)', 'NUM_UNIQUE(pri_cust_asset_acct_info.is_secu_card)', 'NUM_UNIQUE(pri_cust_asset_acct_info.prod_code)', 'NUM_UNIQUE(pri_cust_asset_acct_info.stp_sts)', 'SUM(pri_cust_asset_acct_info.avg_mth)', 'SUM(pri_cust_asset_acct_info.avg_year)', 'SUM(pri_cust_asset_acct_info.bal)', 'COUNT(pri_cust_asset_info)', 'MAX(pri_cust_asset_info.repay_type)', 'MEAN(pri_cust_asset_info.is_extend)', 'MEAN(pri_cust_asset_info.is_mortgage)', 'MEAN(pri_cust_asset_info.overdue_flag)', 'MEAN(pri_cust_asset_info.repay_type)', 'MEAN(pri_cust_asset_info.vouch_type)', 'SUM(pri_cust_asset_info.is_extend)', 'SUM(pri_cust_asset_info.is_mortgage)', 'SUM(pri_cust_asset_info.overdue_flag)', 'SUM(pri_cust_asset_info.repay_type)', 'SUM(pri_cust_asset_info.vouch_type)', 'COUNT(pri_cust_base_info)', 'MODE(pri_cust_base_info.education)', 'MODE(pri_cust_base_info.is_black)', 'MODE(pri_cust_base_info.is_contact)', 'MODE(pri_cust_base_info.is_employee)', 'MODE(pri_cust_base_info.is_mgr_dep)', 'MODE(pri_cust_base_info.is_shareholder)', 'MODE(pri_cust_base_info.marrige)', 'MODE(pri_cust_base_info.prof_titl)', 'NUM_UNIQUE(pri_cust_base_info.education)', 'NUM_UNIQUE(pri_cust_base_info.is_black)', 'NUM_UNIQUE(pri_cust_base_info.is_contact)', 'NUM_UNIQUE(pri_cust_base_info.is_employee)', 'NUM_UNIQUE(pri_cust_base_info.is_mgr_dep)', 'NUM_UNIQUE(pri_cust_base_info.is_shareholder)', 'NUM_UNIQUE(pri_cust_base_info.marrige)', 'NUM_UNIQUE(pri_cust_base_info.prof_titl)', 'COUNT(dm_v_tr_gzdf_mx)', 'MEAN(dm_v_tr_gzdf_mx. tran_amt)', 'MIN(dm_v_tr_gzdf_mx. tran_amt)', 'SUM(dm_v_tr_gzdf_mx. tran_amt)', 'COUNT(dm_v_tr_sbyb_mx)', 'MODE(dm_v_tr_sbyb_mx. tran_sts)', 'NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)']

In [15]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

x_list.remove('Unnamed: 0.1')
x_list.remove('uid')
x_list.remove('star_level')
X = df[x_list]
Y = df['star_level']
model = sm.OLS(Y, X).fit()
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif["features"] = X.columns

D:\anaconda3\envs\data-integration\lib\site-packages\statsmodels\regression\linear_model.py:1754: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.uncentered_tss

In [16]:
print(vif)

    VIF Factor                               features
0     3.225345                   COUNT(dm_v_tr_sa_mx)
1    11.414610            MEAN(dm_v_tr_sa_mx. dr_amt)
2     2.244337            SKEW(dm_v_tr_sa_mx. dr_amt)
3    13.912628             STD(dm_v_tr_sa_mx. dr_amt)
4     5.523185             SUM(dm_v_tr_sa_mx. dr_amt)
..         ...                                    ...
57    2.026930         MIN(dm_v_tr_gzdf_mx. tran_amt)
58    9.988736         SUM(dm_v_tr_gzdf_mx. tran_amt)
59    1.228336                 COUNT(dm_v_tr_sbyb_mx)
60    1.068849        MODE(dm_v_tr_sbyb_mx. tran_sts)
61         NaN  NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)

[62 rows x 2 columns]

In [17]:
vif.to_csv("./star_vif_1.csv")

In [18]:
vif_threshold = 10
high_vif_features = list(vif[vif['VIF Factor'] > vif_threshold]["features"])
high_vif_features

['MEAN(dm_v_tr_sa_mx. dr_amt)',
 'STD(dm_v_tr_sa_mx. dr_amt)',
 'MEAN(pri_cust_asset_acct_info.avg_mth)',
 'MEAN(pri_cust_asset_acct_info.avg_year)',
 'MEAN(pri_cust_asset_acct_info.bal)',
 'SUM(pri_cust_asset_acct_info.avg_mth)',
 'SUM(pri_cust_asset_acct_info.avg_year)',
 'SUM(pri_cust_asset_acct_info.bal)',
 'MAX(pri_cust_asset_info.repay_type)',
 'MEAN(pri_cust_asset_info.is_extend)',
 'MEAN(pri_cust_asset_info.is_mortgage)',
 'MEAN(pri_cust_asset_info.overdue_flag)',
 'MEAN(pri_cust_asset_info.repay_type)',
 'MEAN(pri_cust_asset_info.vouch_type)',
 'SUM(pri_cust_asset_info.is_extend)',
 'SUM(pri_cust_asset_info.is_mortgage)',
 'SUM(pri_cust_asset_info.overdue_flag)',
 'SUM(pri_cust_asset_info.repay_type)',
 'SUM(pri_cust_asset_info.vouch_type)']

In [19]:
print(len(high_vif_features))

19

In [20]:
df.drop(columns=high_vif_features,axis=1,inplace=True)

In [21]:
df.to_csv('./star_after_vif.csv')

In [22]:
df

,Unnamed: 0.1,uid,star_level,COUNT(dm_v_tr_sa_mx),SKEW(dm_v_tr_sa_mx. dr_amt),SUM(dm_v_tr_sa_mx. dr_amt),COUNT(pri_cust_asset_acct_info),MODE(pri_cust_asset_acct_info. acct_char),MODE(pri_cust_asset_acct_info.acct_sts),MODE(pri_cust_asset_acct_info.curr_type),...,NUM_UNIQUE(pri_cust_base_info.is_shareholder),NUM_UNIQUE(pri_cust_base_info.marrige),NUM_UNIQUE(pri_cust_base_info.prof_titl),COUNT(dm_v_tr_gzdf_mx),MEAN(dm_v_tr_gzdf_mx. tran_amt),MIN(dm_v_tr_gzdf_mx. tran_amt),SUM(dm_v_tr_gzdf_mx. tran_amt),COUNT(dm_v_tr_sbyb_mx),MODE(dm_v_tr_sbyb_mx. tran_sts),NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)
0,0,130581199112042682,1,-0.650138,-0.132824,-0.506595,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
1,1,130635198511165690,3,3.190510,2.439056,1.113832,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,3.228379,2.295653,-0.452617,3.531513,-0.635444,-0.308942,0.0
2,2,130684198606215045,1,0.077438,0.298063,0.832935,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
3,3,130802201408149594,1,-0.650138,-0.132824,-0.506595,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
4,4,140902198607183528,1,-0.602428,-1.508162,-0.506595,0.242028,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290653,290653,654324198006010321,1,-0.507008,-0.771415,-0.208672,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.189118,2.652135,3.635567,0.040531,-0.635444,-0.308942,0.0
290654,290654,654326198608203393,2,3.309785,2.439056,3.406533,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,0.121564,3.124384,3.635567,0.834069,-0.635444,-0.308942,0.0
290655,290655,810000200811269255,1,-0.542790,-1.508162,-0.506595,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,0.432245,-1.315002,-0.578950,-0.376641,-0.635444,-0.308942,0.0
290656,290656,830000197007029225,1,-0.566645,-0.763781,-0.499487,0.242028,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,0.419081,3.237170,0.0
290657,290657,830000200706189396,-1,-0.578573,-1.508162,-0.506595,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.189118,-1.167730,-0.201090,-0.366538,-0.635444,-0.308942,0.0

In [23]:
test_df = pd.DataFrame(columns=df.columns)
mask = df['star_level'] == -1
test_df = test_df.append(df.loc[mask])
test_df

C:\Users\10728\AppData\Local\Temp\ipykernel_32284\2996288083.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  test_df = test_df.append(df.loc[mask])

,Unnamed: 0.1,uid,star_level,COUNT(dm_v_tr_sa_mx),SKEW(dm_v_tr_sa_mx. dr_amt),SUM(dm_v_tr_sa_mx. dr_amt),COUNT(pri_cust_asset_acct_info),MODE(pri_cust_asset_acct_info. acct_char),MODE(pri_cust_asset_acct_info.acct_sts),MODE(pri_cust_asset_acct_info.curr_type),...,NUM_UNIQUE(pri_cust_base_info.is_shareholder),NUM_UNIQUE(pri_cust_base_info.marrige),NUM_UNIQUE(pri_cust_base_info.prof_titl),COUNT(dm_v_tr_gzdf_mx),MEAN(dm_v_tr_gzdf_mx. tran_amt),MIN(dm_v_tr_gzdf_mx. tran_amt),SUM(dm_v_tr_gzdf_mx. tran_amt),COUNT(dm_v_tr_sbyb_mx),MODE(dm_v_tr_sbyb_mx. tran_sts),NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)
14,14,220623198601280605,-1,3.309785,1.407637,0.414970,0.242028,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,3.228379,0.304437,-0.578950,1.978982,-0.635444,-0.308942,0.0
23,23,320304194409153817,-1,-0.602428,-1.508162,-0.506595,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
27,27,320821197207219926,-1,-0.590500,-0.483046,0.019952,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
36,36,320911195402222999,-1,1.604155,2.439056,3.406533,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
37,37,320911195606191995,-1,-0.626283,-0.132824,1.336322,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290633,290633,654022199007159342,-1,0.769232,2.439056,0.387434,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,3.228379,2.080890,-0.578950,3.531513,-0.635444,-0.308942,0.0
290641,290641,654123200306289312,-1,-0.614355,-0.714110,-0.468421,0.242028,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,0.419081,3.237170,0.0
290645,290645,654128198506229308,-1,-0.650138,-0.132824,-0.506595,0.242028,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
290649,290649,654323197311259499,-1,-0.602428,-1.508162,-0.506595,0.242028,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
290657,290657,830000200706189396,-1,-0.578573,-1.508162,-0.506595,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.189118,-1.167730,-0.201090,-0.366538,-0.635444,-0.308942,0.0

In [24]:
test_df.to_csv("./star_test.csv")

In [25]:
df = df.drop(df[mask].index)
df

,Unnamed: 0.1,uid,star_level,COUNT(dm_v_tr_sa_mx),SKEW(dm_v_tr_sa_mx. dr_amt),SUM(dm_v_tr_sa_mx. dr_amt),COUNT(pri_cust_asset_acct_info),MODE(pri_cust_asset_acct_info. acct_char),MODE(pri_cust_asset_acct_info.acct_sts),MODE(pri_cust_asset_acct_info.curr_type),...,NUM_UNIQUE(pri_cust_base_info.is_shareholder),NUM_UNIQUE(pri_cust_base_info.marrige),NUM_UNIQUE(pri_cust_base_info.prof_titl),COUNT(dm_v_tr_gzdf_mx),MEAN(dm_v_tr_gzdf_mx. tran_amt),MIN(dm_v_tr_gzdf_mx. tran_amt),SUM(dm_v_tr_gzdf_mx. tran_amt),COUNT(dm_v_tr_sbyb_mx),MODE(dm_v_tr_sbyb_mx. tran_sts),NUM_UNIQUE(dm_v_tr_sbyb_mx. tran_sts)
0,0,130581199112042682,1,-0.650138,-0.132824,-0.506595,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
1,1,130635198511165690,3,3.190510,2.439056,1.113832,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,3.228379,2.295653,-0.452617,3.531513,-0.635444,-0.308942,0.0
2,2,130684198606215045,1,0.077438,0.298063,0.832935,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
3,3,130802201408149594,1,-0.650138,-0.132824,-0.506595,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
4,4,140902198607183528,1,-0.602428,-1.508162,-0.506595,0.242028,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290652,290652,654324198004269794,1,-0.137256,0.537990,3.406533,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,-0.635444,-0.308942,0.0
290653,290653,654324198006010321,1,-0.507008,-0.771415,-0.208672,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.189118,2.652135,3.635567,0.040531,-0.635444,-0.308942,0.0
290654,290654,654326198608203393,2,3.309785,2.439056,3.406533,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,0.121564,3.124384,3.635567,0.834069,-0.635444,-0.308942,0.0
290655,290655,810000200811269255,1,-0.542790,-1.508162,-0.506595,-0.903042,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,0.432245,-1.315002,-0.578950,-0.376641,-0.635444,-0.308942,0.0
290656,290656,830000197007029225,1,-0.566645,-0.763781,-0.499487,0.242028,0.238609,-0.200881,0.0,...,0.0,0.0,0.0,-0.499799,-0.182106,-0.300377,-0.392041,0.419081,3.237170,0.0

In [26]:
df.to_csv("./star_train.csv")